In [ ]:
import numpy as np
import pandas as pd
from pymatgen.core import Structure
from matminer.featurizers.base import MultipleFeaturizer
from matminer.featurizers.composition import ElementProperty, Stoichiometry, ValenceOrbital, IonProperty
from matminer.featurizers.structure import (SiteStatsFingerprint, StructuralHeterogeneity,
                                            ChemicalOrdering, StructureComposition, MaximumPackingEfficiency)
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score,roc_curve,auc
import seaborn as sns

# 1. Read the dataset based on HTC

In [7]:
df = pd.read_json('./data/MP_dataset_C12_HTC.json')
df

,nsites,nelements,formula_pretty,formula_anonymous,volume,density,material_id,energy_per_atom,formation_energy_per_atom,energy_above_hull,band_gap,is_metal,structure_json,label,k_ao,k_log
0,14,3,Cs(SbS2)2,AB2C4,416.924169,4.020155,mp-8890,-16.138279,-0.616589,0.000000,1.4413,False,"{'@module': 'pymatgen.core.structure', '@class...",1,0.252145,-0.598350
1,5,3,KGeBr3,ABC3,175.640517,3.322678,mp-998412,-3.495008,-1.412312,0.025231,0.9083,False,"{'@module': 'pymatgen.core.structure', '@class...",1,0.186959,-0.728253
2,4,3,LiAgF2,ABC2,51.295990,4.946592,mp-1176792,-9.631004,-2.133530,0.023437,1.8912,False,"{'@module': 'pymatgen.core.structure', '@class...",1,0.413129,-0.383914
3,6,2,Sb2Os,AB2,130.076043,11.074427,mp-2695,-34.883281,-0.083994,0.000000,0.3447,False,"{'@module': 'pymatgen.core.structure', '@class...",0,19.029568,1.279429
4,12,3,LiAgF4,ABC4,150.435277,4.212250,mp-752768,-7.883206,-1.843673,0.035738,1.1186,False,"{'@module': 'pymatgen.core.structure', '@class...",1,0.603420,-0.219381
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,14,3,In5AgSe8,AB5C8,408.163709,5.344296,mp-1224092,-3.944965,-0.758815,0.000000,0.2236,False,"{'@module': 'pymatgen.core.structure', '@class...",1,0.102742,-0.988251
657,8,3,GeTe4Pb3,AB3C4,269.026576,7.435517,mp-1224448,-35.894271,-0.344737,0.042003,0.6227,False,"{'@module': 'pymatgen.core.structure', '@class...",0,3.540820,0.549104
658,7,3,Tl3AsS3,AB3C3,193.649007,6.725080,mp-9791,-3.978961,-0.521873,0.006070,1.2156,False,"{'@module': 'pymatgen.core.structure', '@class...",0,0.107991,-0.966613
659,18,3,Li2PdF6,AB2C6,189.318076,4.110032,mp-13985,-7.451218,-2.287240,0.000000,1.6749,False,"{'@module': 'pymatgen.core.structure', '@class...",1,1.613321,0.207721
660,7,3,Tl3SbS3,AB3C3,203.052508,6.796676,mp-8393,-3.928824,-0.549039,0.000000,1.5920,False,"{'@module': 'pymatgen.core.structure', '@class...",0,0.142026,-0.847633

In [8]:
df['structure'] = df['structure_json'].apply(lambda x: Structure.from_dict(x, fmt='json'))

In [9]:
df.columns

Index(['nsites', 'nelements', 'formula_pretty', 'formula_anonymous', 'volume',
       'density', 'material_id', 'energy_per_atom',
       'formation_energy_per_atom', 'energy_above_hull', 'band_gap',
       'is_metal', 'structure_json', 'label', 'k_ao', 'k_log', 'structure'],
      dtype='object')

# 2. Feature generation

In [10]:
featurizer = MultipleFeaturizer([
    SiteStatsFingerprint.from_preset("CoordinationNumber_ward-prb-2017"),
    StructuralHeterogeneity(),
    ChemicalOrdering(),  
    
    MaximumPackingEfficiency(),
    SiteStatsFingerprint.from_preset("LocalPropertyDifference_ward-prb-2017"),
    StructureComposition(Stoichiometry()),
    StructureComposition(ElementProperty.from_preset("magpie")),
    StructureComposition(ValenceOrbital(props=['frac'])),
    StructureComposition(IonProperty(fast=True))
])

df_fea = featurizer.featurize_dataframe(df, col_id="structure")
df_fea.head()

MultipleFeaturizer:   0%|          | 0/661 [00:00<?, ?it/s]

,nsites,nelements,formula_pretty,formula_anonymous,volume,density,material_id,energy_per_atom,formation_energy_per_atom,energy_above_hull,...,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,frac s valence electrons,frac p valence electrons,frac d valence electrons,frac f valence electrons,compound possible,max ionic char,avg ionic char
0,14,3,Cs(SbS2)2,AB2C4,416.924169,4.020155,mp-8890,-16.138279,-0.616589,0.000000,...,120.142857,57.306122,70.0,0.236364,0.400000,0.363636,0.000000,False,0.551131,0.069434
1,5,3,KGeBr3,ABC3,175.640517,3.322678,mp-998412,-3.495008,-1.412312,0.025231,...,129.200000,78.240000,64.0,0.136364,0.257576,0.606061,0.000000,True,0.681744,0.117973
2,4,3,LiAgF2,ABC2,51.295990,4.946592,mp-1176792,-9.631004,-2.133530,0.023437,...,121.000000,106.000000,15.0,0.230769,0.384615,0.384615,0.000000,True,0.894601,0.205734
3,6,2,Sb2Os,AB2,130.076043,11.074427,mp-2695,-34.883281,-0.083994,0.000000,...,175.333333,12.444444,166.0,0.115385,0.115385,0.500000,0.269231,False,0.005609,0.001246
4,12,3,LiAgF4,ABC4,150.435277,4.212250,mp-752768,-7.883206,-1.843673,0.035738,...,85.666667,94.222222,15.0,0.250000,0.500000,0.250000,0.000000,False,0.894601,0.177264

In [11]:
df_fea['k_class'] = 1

df_fea.loc[df_fea['k_ao'] > 2, 'k_class'] = 0

In [12]:
count_0 = (df_fea['k_class'] == 0).sum()
count_0

217

In [13]:
count_1 = (df_fea['k_class'] == 1).sum()
count_1

444

In [14]:
X = df_fea.drop(['nsites', 'nelements', 'formula_pretty', 'formula_anonymous', 'volume',
       'density', 'material_id', 'energy_per_atom',
       'formation_energy_per_atom', 'energy_above_hull', 'band_gap',
       'is_metal', 'structure_json', 'label', 'k_ao', 'k_log', 'structure',
                'k_class'], axis = 1)

X

,minimum CN_VoronoiNN,maximum CN_VoronoiNN,range CN_VoronoiNN,mean CN_VoronoiNN,avg_dev CN_VoronoiNN,mean absolute deviation in relative bond length,max relative bond length,min relative bond length,minimum neighbor distance variation,maximum neighbor distance variation,...,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber,frac s valence electrons,frac p valence electrons,frac d valence electrons,frac f valence electrons,compound possible,max ionic char,avg ionic char
0,7.451238,11.852844,4.401606,9.317722,1.006927,0.042590,1.130923,0.924097,5.462055e-02,0.202398,...,120.142857,57.306122,70.0,0.236364,0.400000,0.363636,0.000000,False,0.551131,0.069434
1,5.969593,12.005647,6.036054,10.608924,1.855732,0.084987,1.117352,0.787531,1.209678e-02,0.123635,...,129.200000,78.240000,64.0,0.136364,0.257576,0.606061,0.000000,True,0.681744,0.117973
2,6.000000,7.420072,1.420072,6.935351,0.484721,0.064891,1.115926,0.870218,1.054413e-07,0.178886,...,121.000000,106.000000,15.0,0.230769,0.384615,0.384615,0.000000,True,0.894601,0.205734
3,7.211076,9.414104,2.203028,8.679761,0.979123,0.053056,1.039792,0.920416,4.406832e-02,0.127974,...,175.333333,12.444444,166.0,0.115385,0.115385,0.500000,0.269231,False,0.005609,0.001246
4,7.100904,11.240964,4.140060,10.010793,1.640227,0.054177,1.040632,0.903046,1.442192e-16,0.157342,...,85.666667,94.222222,15.0,0.250000,0.500000,0.250000,0.000000,False,0.894601,0.177264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,5.741111,6.818940,1.077829,6.311252,0.384054,0.040734,1.048487,0.944346,1.559733e-01,0.203981,...,73.714286,68.244898,14.0,0.132353,0.181373,0.686275,0.000000,True,0.137763,0.031998
657,5.996431,6.443000,0.446569,6.273414,0.137653,0.007729,1.021094,0.973891,5.657788e-03,0.039081,...,188.500000,36.500000,152.0,0.098765,0.148148,0.493827,0.259259,True,0.025275,0.003775
658,7.077826,11.605190,4.527365,10.017743,1.360668,0.056295,1.065678,0.881517,9.032000e-02,0.258359,...,136.857143,57.306122,70.0,0.122807,0.157895,0.350877,0.368421,True,0.205784,0.044814
659,5.999997,11.824808,5.824811,9.781023,2.515332,0.099357,1.078966,0.830062,6.322125e-04,0.170943,...,85.888889,94.518519,15.0,0.259259,0.555556,0.185185,0.000000,True,0.894601,0.180732
660,7.766528,10.594732,2.828204,9.652573,0.807564,0.048544,1.056635,0.919246,9.667138e-02,0.221099,...,136.857143,57.306122,70.0,0.122807,0.157895,0.350877,0.368421,True,0.205784,0.044715

In [15]:
y = df_fea["k_class"]
y

0      1
1      1
2      1
3      0
4      1
      ..
656    1
657    0
658    1
659    1
660    1
Name: k_class, Length: 661, dtype: int64

# 3. Compare different models based on 10-fold cross validation

In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

kfold = StratifiedKFold(n_splits=10, random_state=19981024, shuffle=True)

In [18]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.8878433687524596
0.8245816372682044

In [19]:
from xgboost import XGBClassifier

clf = XGBClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.873856967947877
0.8154681139755766

In [34]:
from sklearn.ensemble import GradientBoostingClassifier
## 定义 GBC模型 
clf =GradientBoostingClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.883107044470681
0.8215287200361827

In [35]:
from lightgbm import LGBMClassifier

## 定义 LightGBM 模型 
clf = LGBMClassifier(random_state=1998)
#scores = cross_val_score(clf, X_ss, y, cv=kfold, scoring = 'accuracy')
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 195, number of negative: 399
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011336 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 27336
[LightGBM] [Info] Number of data points in the train set: 594, number of used features: 244
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.328283 -> initscore=-0.715962
[LightGBM] [Info] Start training from score -0.715962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 196, number of negative: 399
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003444 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 27349
[LightGBM] [Info] Number of data points in the train set: 595, number of used features: 244
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.329412 -> initscore=-0.710847
[LightGBM] [Info] Start training from score -0.710847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 196, number of negative: 399
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005358 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 27355
[LightGBM] [Info] Number of data points in the train set: 595, number of used features: 244
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.329412 -> initscore=-0.710847
[LightGBM] [Info] Start training from score -0.710847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [37]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.7496608946608947
0.7805970149253731

In [38]:
from sklearn.ensemble import ExtraTreesClassifier

clf = ExtraTreesClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.8761862674362675
0.815513342379014

In [16]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.8663123660850933
0.8184305744007236

In [15]:
from catboost import CatBoostClassifier

clf = CatBoostClassifier(random_state=1998)
scores = cross_val_score(clf, X, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

Learning rate set to 0.008248
0:	learn: 0.6889671	total: 83ms	remaining: 1m 22s
1:	learn: 0.6845493	total: 90.8ms	remaining: 45.3s
2:	learn: 0.6792496	total: 97.8ms	remaining: 32.5s
3:	learn: 0.6741088	total: 104ms	remaining: 26s
4:	learn: 0.6695852	total: 111ms	remaining: 22.1s
5:	learn: 0.6653066	total: 118ms	remaining: 19.5s
6:	learn: 0.6602068	total: 124ms	remaining: 17.6s
7:	learn: 0.6559006	total: 130ms	remaining: 16.1s
8:	learn: 0.6524844	total: 136ms	remaining: 15s
9:	learn: 0.6488114	total: 141ms	remaining: 14s
10:	learn: 0.6434232	total: 148ms	remaining: 13.3s
11:	learn: 0.6394151	total: 154ms	remaining: 12.7s
12:	learn: 0.6352490	total: 160ms	remaining: 12.2s
13:	learn: 0.6305561	total: 166ms	remaining: 11.7s
14:	learn: 0.6264968	total: 172ms	remaining: 11.3s
15:	learn: 0.6227788	total: 178ms	remaining: 10.9s
16:	learn: 0.6182830	total: 184ms	remaining: 10.6s
17:	learn: 0.6144694	total: 190ms	remaining: 10.4s
18:	learn: 0.6102869	total: 196ms	remaining: 10.1s
19:	learn: 0.6062234	total: 201ms	remaining: 9.84s
20:	learn: 0.6026385	total: 206ms	remaining: 9.63s
21:	learn: 0.5993947	total: 212ms	remaining: 9.41s
22:	learn: 0.5958152	total: 218ms	remaining: 9.25s
23:	learn: 0.5915014	total: 223ms	remaining: 9.08s
24:	learn: 0.5881820	total: 228ms	remaining: 8.89s
25:	learn: 0.5835956	total: 234ms	remaining: 8.76s
26:	learn: 0.5798888	total: 239ms	remaining: 8.63s
27:	learn: 0.5768120	total: 245ms	remaining: 8.51s
28:	learn: 0.5742455	total: 251ms	remaining: 8.39s
29:	learn: 0.5713620	total: 256ms	remaining: 8.28s
30:	learn: 0.5683988	total: 262ms	remaining: 8.18s
31:	learn: 0.5641705	total: 268ms	remaining: 8.09s
32:	learn: 0.5605320	total: 273ms	remaining: 7.99s
33:	learn: 0.5573770	total: 278ms	remaining: 7.9s
34:	learn: 0.5549949	total: 283ms	remaining: 7.81s
35:	learn: 0.5525353	total: 289ms	remaining: 7.73s
36:	learn: 0.5496038	total: 294ms	remaining: 7.66s
37:	learn: 0.5462462	total: 299ms	remaining: 7.57s
38:	learn: 0.5434292	total: 305ms	remaining: 7.5s
39:	learn: 0.5405688	total: 310ms	remaining: 7.45s
40:	learn: 0.5383263	total: 316ms	remaining: 7.39s
41:	learn: 0.5361499	total: 322ms	remaining: 7.34s
42:	learn: 0.5333651	total: 327ms	remaining: 7.28s
43:	learn: 0.5309774	total: 332ms	remaining: 7.22s
44:	learn: 0.5283580	total: 338ms	remaining: 7.17s
45:	learn: 0.5261911	total: 344ms	remaining: 7.13s
46:	learn: 0.5231203	total: 349ms	remaining: 7.08s
47:	learn: 0.5200167	total: 355ms	remaining: 7.04s
48:	learn: 0.5172414	total: 366ms	remaining: 7.1s
49:	learn: 0.5150959	total: 370ms	remaining: 7.03s
50:	learn: 0.5127515	total: 375ms	remaining: 6.97s
51:	learn: 0.5097548	total: 380ms	remaining: 6.93s
52:	learn: 0.5073193	total: 386ms	remaining: 6.9s
53:	learn: 0.5047559	total: 392ms	remaining: 6.86s
54:	learn: 0.5024333	total: 397ms	remaining: 6.83s
55:	learn: 0.5001478	total: 403ms	remaining: 6.8s
56:	learn: 0.4979407	total: 408ms	remaining: 6.76s
57:	learn: 0.4951071	total: 414ms	remaining: 6.72s
58:	learn: 0.4931456	total: 419ms	remaining: 6.68s
59:	learn: 0.4906342	total: 424ms	remaining: 6.64s
60:	learn: 0.4884509	total: 429ms	remaining: 6.61s
61:	learn: 0.4866527	total: 435ms	remaining: 6.59s
62:	learn: 0.4844394	total: 441ms	remaining: 6.56s
63:	learn: 0.4825596	total: 446ms	remaining: 6.52s
64:	learn: 0.4806251	total: 452ms	remaining: 6.5s
65:	learn: 0.4783572	total: 457ms	remaining: 6.47s
66:	learn: 0.4767869	total: 463ms	remaining: 6.45s
67:	learn: 0.4748537	total: 469ms	remaining: 6.42s
68:	learn: 0.4729473	total: 474ms	remaining: 6.4s
69:	learn: 0.4704475	total: 480ms	remaining: 6.38s
70:	learn: 0.4681364	total: 487ms	remaining: 6.37s
71:	learn: 0.4668057	total: 492ms	remaining: 6.35s
72:	learn: 0.4651622	total: 498ms	remaining: 6.32s
73:	learn: 0.4635203	total: 504ms	remaining: 6.3s
74:	learn: 0.4617874	total: 509ms	remaining: 6.28s
75:	learn: 0.4597201	total: 515ms	remaining: 6.26s
76:	learn: 0.4575872	total: 520ms	remaining: 6.24s
77:	learn: 0.4551456	total: 526ms	remaining: 6.22s
78:	learn: 0.4532423	total: 531ms	remaining: 6.19s
79:	learn: 0.4516464	total: 537ms	remaining: 6.17s
80:	learn: 0.4497874	total: 542ms	remaining: 6.15s
81:	learn: 0.4483348	total: 547ms	remaining: 6.13s
82:	learn: 0.4468037	total: 553ms	remaining: 6.11s
83:	learn: 0.4450962	total: 558ms	remaining: 6.09s
84:	learn: 0.4435763	total: 564ms	remaining: 6.07s
85:	learn: 0.4418660	total: 570ms	remaining: 6.06s
86:	learn: 0.4398234	total: 575ms	remaining: 6.04s
87:	learn: 0.4376765	total: 580ms	remaining: 6.01s
88:	learn: 0.4359020	total: 586ms	remaining: 5.99s
89:	learn: 0.4342520	total: 591ms	remaining: 5.98s
90:	learn: 0.4324628	total: 597ms	remaining: 5.97s
91:	learn: 0.4314130	total: 603ms	remaining: 5.95s
92:	learn: 0.4300858	total: 609ms	remaining: 5.94s
93:	learn: 0.4281950	total: 615ms	remaining: 5.92s
94:	learn: 0.4261813	total: 620ms	remaining: 5.91s
95:	learn: 0.4247942	total: 625ms	remaining: 5.88s
96:	learn: 0.4227704	total: 630ms	remaining: 5.87s
97:	learn: 0.4212913	total: 636ms	remaining: 5.85s
98:	learn: 0.4196795	total: 642ms	remaining: 5.84s
99:	learn: 0.4182666	total: 647ms	remaining: 5.83s
100:	learn: 0.4173427	total: 653ms	remaining: 5.81s
101:	learn: 0.4160609	total: 659ms	remaining: 5.8s
102:	learn: 0.4147949	total: 666ms	remaining: 5.8s
103:	learn: 0.4136443	total: 671ms	remaining: 5.78s
104:	learn: 0.4122586	total: 677ms	remaining: 5.77s
105:	learn: 0.4107736	total: 683ms	remaining: 5.76s
106:	learn: 0.4098413	total: 689ms	remaining: 5.75s
107:	learn: 0.4078336	total: 695ms	remaining: 5.74s
108:	learn: 0.4066215	total: 700ms	remaining: 5.72s
109:	learn: 0.4053011	total: 706ms	remaining: 5.71s
110:	learn: 0.4039667	total: 711ms	remaining: 5.7s
111:	learn: 0.4027083	total: 717ms	remaining: 5.69s
112:	learn: 0.4015501	total: 723ms	remaining: 5.68s
113:	learn: 0.4004453	total: 729ms	remaining: 5.67s
114:	learn: 0.3990446	total: 735ms	remaining: 5.66s
115:	learn: 0.3977228	total: 741ms	remaining: 5.64s
116:	learn: 0.3962853	total: 746ms	remaining: 5.63s
117:	learn: 0.3952035	total: 752ms	remaining: 5.62s
118:	learn: 0.3938522	total: 758ms	remaining: 5.61s
119:	learn: 0.3925056	total: 763ms	remaining: 5.6s
120:	learn: 0.3912553	total: 768ms	remaining: 5.58s
121:	learn: 0.3900137	total: 773ms	remaining: 5.56s
122:	learn: 0.3889556	total: 779ms	remaining: 5.55s
123:	learn: 0.3877182	total: 784ms	remaining: 5.54s
124:	learn: 0.3866104	total: 790ms	remaining: 5.53s
125:	learn: 0.3857468	total: 796ms	remaining: 5.52s
126:	learn: 0.3845912	total: 801ms	remaining: 5.5s
127:	learn: 0.3837440	total: 806ms	remaining: 5.49s
128:	learn: 0.3827732	total: 812ms	remaining: 5.48s
129:	learn: 0.3818829	total: 817ms	remaining: 5.47s
130:	learn: 0.3810800	total: 823ms	remaining: 5.46s
131:	learn: 0.3802183	total: 829ms	remaining: 5.45s
132:	learn: 0.3791834	total: 835ms	remaining: 5.44s
133:	learn: 0.3780156	total: 840ms	remaining: 5.43s
134:	learn: 0.3770038	total: 845ms	remaining: 5.42s
135:	learn: 0.3756036	total: 851ms	remaining: 5.4s
136:	learn: 0.3747684	total: 856ms	remaining: 5.39s
137:	learn: 0.3741643	total: 862ms	remaining: 5.38s
138:	learn: 0.3732295	total: 868ms	remaining: 5.37s
139:	learn: 0.3719963	total: 874ms	remaining: 5.37s
140:	learn: 0.3712880	total: 879ms	remaining: 5.36s
141:	learn: 0.3703430	total: 884ms	remaining: 5.34s
142:	learn: 0.3695192	total: 890ms	remaining: 5.33s
143:	learn: 0.3685745	total: 896ms	remaining: 5.32s
144:	learn: 0.3678892	total: 901ms	remaining: 5.32s
145:	learn: 0.3671529	total: 907ms	remaining: 5.31s
146:	learn: 0.3664566	total: 913ms	remaining: 5.3s
147:	learn: 0.3655825	total: 918ms	remaining: 5.29s
148:	learn: 0.3648809	total: 923ms	remaining: 5.27s
149:	learn: 0.3642291	total: 929ms	remaining: 5.26s
150:	learn: 0.3632760	total: 934ms	remaining: 5.25s
151:	learn: 0.3621333	total: 940ms	remaining: 5.25s
152:	learn: 0.3612191	total: 945ms	remaining: 5.23s
153:	learn: 0.3604482	total: 951ms	remaining: 5.22s
154:	learn: 0.3591480	total: 957ms	remaining: 5.21s
155:	learn: 0.3580545	total: 962ms	remaining: 5.21s
156:	learn: 0.3573040	total: 968ms	remaining: 5.2s
157:	learn: 0.3560472	total: 973ms	remaining: 5.19s
158:	learn: 0.3552315	total: 979ms	remaining: 5.18s
159:	learn: 0.3544791	total: 984ms	remaining: 5.17s
160:	learn: 0.3535885	total: 989ms	remaining: 5.16s
161:	learn: 0.3525206	total: 996ms	remaining: 5.15s
162:	learn: 0.3517486	total: 1s	remaining: 5.14s
163:	learn: 0.3508325	total: 1.01s	remaining: 5.13s
164:	learn: 0.3500133	total: 1.01s	remaining: 5.12s
165:	learn: 0.3492862	total: 1.02s	remaining: 5.11s
166:	learn: 0.3486742	total: 1.02s	remaining: 5.11s
167:	learn: 0.3480337	total: 1.03s	remaining: 5.09s
168:	learn: 0.3473927	total: 1.03s	remaining: 5.09s
169:	learn: 0.3466484	total: 1.04s	remaining: 5.07s
170:	learn: 0.3456318	total: 1.04s	remaining: 5.06s
171:	learn: 0.3449314	total: 1.05s	remaining: 5.05s
172:	learn: 0.3441166	total: 1.05s	remaining: 5.04s
173:	learn: 0.3431419	total: 1.06s	remaining: 5.04s
174:	learn: 0.3419165	total: 1.07s	remaining: 5.03s
175:	learn: 0.3414095	total: 1.07s	remaining: 5.02s
176:	learn: 0.3406228	total: 1.08s	remaining: 5.01s
177:	learn: 0.3398585	total: 1.08s	remaining: 5s
178:	learn: 0.3392621	total: 1.09s	remaining: 4.99s
179:	learn: 0.3381799	total: 1.09s	remaining: 4.98s
180:	learn: 0.3370927	total: 1.1s	remaining: 4.97s
181:	learn: 0.3363749	total: 1.1s	remaining: 4.97s
182:	learn: 0.3351796	total: 1.11s	remaining: 4.95s
183:	learn: 0.3345836	total: 1.11s	remaining: 4.95s
184:	learn: 0.3338426	total: 1.12s	remaining: 4.94s
185:	learn: 0.3329752	total: 1.13s	remaining: 4.93s
186:	learn: 0.3325074	total: 1.13s	remaining: 4.92s
187:	learn: 0.3320608	total: 1.14s	remaining: 4.91s
188:	learn: 0.3312360	total: 1.14s	remaining: 4.91s
189:	learn: 0.3304384	total: 1.15s	remaining: 4.9s
190:	learn: 0.3296682	total: 1.15s	remaining: 4.89s
191:	learn: 0.3288608	total: 1.16s	remaining: 4.88s
192:	learn: 0.3279880	total: 1.17s	remaining: 4.87s
193:	learn: 0.3273690	total: 1.17s	remaining: 4.86s
194:	learn: 0.3267317	total: 1.18s	remaining: 4.86s
195:	learn: 0.3259479	total: 1.18s	remaining: 4.85s
196:	learn: 0.3255701	total: 1.19s	remaining: 4.84s
197:	learn: 0.3245806	total: 1.19s	remaining: 4.83s
198:	learn: 0.3236409	total: 1.2s	remaining: 4.83s
199:	learn: 0.3227877	total: 1.2s	remaining: 4.82s
200:	learn: 0.3218142	total: 1.21s	remaining: 4.81s
201:	learn: 0.3214230	total: 1.21s	remaining: 4.8s
202:	learn: 0.3205792	total: 1.22s	remaining: 4.79s
203:	learn: 0.3200209	total: 1.23s	remaining: 4.79s
204:	learn: 0.3192741	total: 1.23s	remaining: 4.78s
205:	learn: 0.3187005	total: 1.24s	remaining: 4.77s
206:	learn: 0.3180524	total: 1.24s	remaining: 4.76s
207:	learn: 0.3174475	total: 1.25s	remaining: 4.75s
208:	learn: 0.3166709	total: 1.25s	remaining: 4.74s
209:	learn: 0.3161831	total: 1.26s	remaining: 4.74s
210:	learn: 0.3155422	total: 1.26s	remaining: 4.73s
211:	learn: 0.3149720	total: 1.27s	remaining: 4.72s
212:	learn: 0.3142017	total: 1.28s	remaining: 4.72s
213:	learn: 0.3136243	total: 1.28s	remaining: 4.72s
214:	learn: 0.3129115	total: 1.29s	remaining: 4.71s
215:	learn: 0.3123797	total: 1.3s	remaining: 4.7s
216:	learn: 0.3118283	total: 1.3s	remaining: 4.7s
217:	learn: 0.3112201	total: 1.31s	remaining: 4.69s
218:	learn: 0.3106146	total: 1.31s	remaining: 4.68s
219:	learn: 0.3099032	total: 1.32s	remaining: 4.67s
220:	learn: 0.3091790	total: 1.32s	remaining: 4.66s
221:	learn: 0.3085411	total: 1.33s	remaining: 4.65s
222:	learn: 0.3079020	total: 1.33s	remaining: 4.65s
223:	learn: 0.3074636	total: 1.34s	remaining: 4.64s
224:	learn: 0.3068538	total: 1.34s	remaining: 4.63s
225:	learn: 0.3061696	total: 1.35s	remaining: 4.63s
226:	learn: 0.3055482	total: 1.36s	remaining: 4.62s
227:	learn: 0.3048535	total: 1.36s	remaining: 4.61s
228:	learn: 0.3042907	total: 1.37s	remaining: 4.6s
229:	learn: 0.3038097	total: 1.37s	remaining: 4.59s
230:	learn: 0.3034186	total: 1.38s	remaining: 4.58s
231:	learn: 0.3029211	total: 1.38s	remaining: 4.58s
232:	learn: 0.3022870	total: 1.39s	remaining: 4.57s
233:	learn: 0.3016087	total: 1.41s	remaining: 4.6s
234:	learn: 0.3010689	total: 1.41s	remaining: 4.59s
235:	learn: 0.3003681	total: 1.42s	remaining: 4.59s
236:	learn: 0.2997156	total: 1.42s	remaining: 4.58s
237:	learn: 0.2991251	total: 1.43s	remaining: 4.57s
238:	learn: 0.2983500	total: 1.43s	remaining: 4.56s
239:	learn: 0.2979473	total: 1.44s	remaining: 4.55s
240:	learn: 0.2974766	total: 1.44s	remaining: 4.54s
241:	learn: 0.2970355	total: 1.45s	remaining: 4.53s
242:	learn: 0.2964294	total: 1.45s	remaining: 4.52s
243:	learn: 0.2959740	total: 1.46s	remaining: 4.52s
244:	learn: 0.2953926	total: 1.46s	remaining: 4.51s
245:	learn: 0.2947235	total: 1.47s	remaining: 4.5s
246:	learn: 0.2941367	total: 1.47s	remaining: 4.49s
247:	learn: 0.2935646	total: 1.48s	remaining: 4.49s
248:	learn: 0.2928835	total: 1.49s	remaining: 4.48s
249:	learn: 0.2922817	total: 1.49s	remaining: 4.47s
250:	learn: 0.2917585	total: 1.5s	remaining: 4.46s
251:	learn: 0.2911694	total: 1.5s	remaining: 4.46s
252:	learn: 0.2905366	total: 1.51s	remaining: 4.45s
253:	learn: 0.2899777	total: 1.51s	remaining: 4.44s
254:	learn: 0.2894079	total: 1.52s	remaining: 4.43s
255:	learn: 0.2889230	total: 1.52s	remaining: 4.42s
256:	learn: 0.2882978	total: 1.53s	remaining: 4.42s
257:	learn: 0.2878085	total: 1.53s	remaining: 4.41s
258:	learn: 0.2870732	total: 1.54s	remaining: 4.4s
259:	learn: 0.2867207	total: 1.54s	remaining: 4.39s
260:	learn: 0.2860110	total: 1.55s	remaining: 4.39s
261:	learn: 0.2853595	total: 1.55s	remaining: 4.38s
262:	learn: 0.2845601	total: 1.56s	remaining: 4.38s
263:	learn: 0.2842265	total: 1.57s	remaining: 4.37s
264:	learn: 0.2836165	total: 1.57s	remaining: 4.36s
265:	learn: 0.2831562	total: 1.58s	remaining: 4.36s
266:	learn: 0.2826441	total: 1.58s	remaining: 4.35s
267:	learn: 0.2821671	total: 1.59s	remaining: 4.34s
268:	learn: 0.2819150	total: 1.59s	remaining: 4.33s
269:	learn: 0.2813550	total: 1.6s	remaining: 4.33s
270:	learn: 0.2808283	total: 1.61s	remaining: 4.32s
271:	learn: 0.2804517	total: 1.61s	remaining: 4.31s
272:	learn: 0.2799343	total: 1.62s	remaining: 4.31s
273:	learn: 0.2793113	total: 1.62s	remaining: 4.3s
274:	learn: 0.2788109	total: 1.63s	remaining: 4.29s
275:	learn: 0.2783784	total: 1.63s	remaining: 4.28s
276:	learn: 0.2782219	total: 1.64s	remaining: 4.27s
277:	learn: 0.2777031	total: 1.64s	remaining: 4.26s
278:	learn: 0.2773532	total: 1.65s	remaining: 4.26s
279:	learn: 0.2768912	total: 1.65s	remaining: 4.25s
280:	learn: 0.2762054	total: 1.66s	remaining: 4.24s
281:	learn: 0.2757841	total: 1.66s	remaining: 4.23s
282:	learn: 0.2752538	total: 1.67s	remaining: 4.23s
283:	learn: 0.2746242	total: 1.67s	remaining: 4.22s
284:	learn: 0.2741133	total: 1.68s	remaining: 4.21s
285:	learn: 0.2736947	total: 1.68s	remaining: 4.2s
286:	learn: 0.2733217	total: 1.69s	remaining: 4.2s
287:	learn: 0.2728336	total: 1.69s	remaining: 4.19s
288:	learn: 0.2723455	total: 1.7s	remaining: 4.18s
289:	learn: 0.2718702	total: 1.71s	remaining: 4.17s
290:	learn: 0.2713667	total: 1.71s	remaining: 4.17s
291:	learn: 0.2710620	total: 1.72s	remaining: 4.16s
292:	learn: 0.2704935	total: 1.72s	remaining: 4.15s
293:	learn: 0.2700549	total: 1.73s	remaining: 4.14s
294:	learn: 0.2697424	total: 1.73s	remaining: 4.14s
295:	learn: 0.2693450	total: 1.74s	remaining: 4.13s
296:	learn: 0.2688767	total: 1.74s	remaining: 4.12s
297:	learn: 0.2684276	total: 1.75s	remaining: 4.12s
298:	learn: 0.2680897	total: 1.75s	remaining: 4.11s
299:	learn: 0.2677198	total: 1.76s	remaining: 4.1s
300:	learn: 0.2674315	total: 1.76s	remaining: 4.09s
301:	learn: 0.2668291	total: 1.77s	remaining: 4.09s
302:	learn: 0.2665401	total: 1.77s	remaining: 4.08s
303:	learn: 0.2660975	total: 1.78s	remaining: 4.08s
304:	learn: 0.2657655	total: 1.78s	remaining: 4.07s
305:	learn: 0.2652791	total: 1.79s	remaining: 4.06s
306:	learn: 0.2648790	total: 1.8s	remaining: 4.06s
307:	learn: 0.2644596	total: 1.8s	remaining: 4.05s
308:	learn: 0.2639477	total: 1.81s	remaining: 4.04s
309:	learn: 0.2634240	total: 1.81s	remaining: 4.04s
310:	learn: 0.2631526	total: 1.82s	remaining: 4.03s
311:	learn: 0.2627703	total: 1.82s	remaining: 4.02s
312:	learn: 0.2624106	total: 1.83s	remaining: 4.02s
313:	learn: 0.2620421	total: 1.84s	remaining: 4.01s
314:	learn: 0.2616153	total: 1.84s	remaining: 4s
315:	learn: 0.2612826	total: 1.85s	remaining: 4s
316:	learn: 0.2609558	total: 1.85s	remaining: 3.99s
317:	learn: 0.2605272	total: 1.86s	remaining: 3.99s
318:	learn: 0.2601677	total: 1.86s	remaining: 3.98s
319:	learn: 0.2596202	total: 1.87s	remaining: 3.97s
320:	learn: 0.2589263	total: 1.87s	remaining: 3.96s
321:	learn: 0.2586622	total: 1.88s	remaining: 3.96s
322:	learn: 0.2581663	total: 1.89s	remaining: 3.95s
323:	learn: 0.2578060	total: 1.89s	remaining: 3.94s
324:	learn: 0.2572721	total: 1.9s	remaining: 3.94s
325:	learn: 0.2569935	total: 1.9s	remaining: 3.93s
326:	learn: 0.2565365	total: 1.91s	remaining: 3.92s
327:	learn: 0.2562229	total: 1.91s	remaining: 3.92s
328:	learn: 0.2558793	total: 1.92s	remaining: 3.91s
329:	learn: 0.2552841	total: 1.92s	remaining: 3.91s
330:	learn: 0.2549952	total: 1.93s	remaining: 3.9s
331:	learn: 0.2546143	total: 1.93s	remaining: 3.89s
332:	learn: 0.2541406	total: 1.94s	remaining: 3.88s
333:	learn: 0.2538362	total: 1.95s	remaining: 3.88s
334:	learn: 0.2535451	total: 1.95s	remaining: 3.87s
335:	learn: 0.2528939	total: 1.96s	remaining: 3.87s
336:	learn: 0.2523681	total: 1.96s	remaining: 3.86s
337:	learn: 0.2520429	total: 1.97s	remaining: 3.85s
338:	learn: 0.2516024	total: 1.97s	remaining: 3.85s
339:	learn: 0.2513636	total: 1.98s	remaining: 3.84s
340:	learn: 0.2509828	total: 1.98s	remaining: 3.83s
341:	learn: 0.2506520	total: 1.99s	remaining: 3.83s
342:	learn: 0.2502712	total: 1.99s	remaining: 3.82s
343:	learn: 0.2499271	total: 2s	remaining: 3.81s
344:	learn: 0.2495781	total: 2.01s	remaining: 3.81s
345:	learn: 0.2491412	total: 2.01s	remaining: 3.8s
346:	learn: 0.2488562	total: 2.02s	remaining: 3.79s
347:	learn: 0.2485758	total: 2.02s	remaining: 3.79s
348:	learn: 0.2481023	total: 2.03s	remaining: 3.78s
349:	learn: 0.2476533	total: 2.03s	remaining: 3.77s
350:	learn: 0.2472849	total: 2.04s	remaining: 3.77s
351:	learn: 0.2467164	total: 2.04s	remaining: 3.76s
352:	learn: 0.2462440	total: 2.05s	remaining: 3.75s
353:	learn: 0.2458283	total: 2.05s	remaining: 3.75s
354:	learn: 0.2454453	total: 2.06s	remaining: 3.74s
355:	learn: 0.2450593	total: 2.06s	remaining: 3.74s
356:	learn: 0.2446030	total: 2.07s	remaining: 3.73s
357:	learn: 0.2442246	total: 2.08s	remaining: 3.72s
358:	learn: 0.2438600	total: 2.08s	remaining: 3.72s
359:	learn: 0.2435045	total: 2.09s	remaining: 3.71s
360:	learn: 0.2431879	total: 2.09s	remaining: 3.7s
361:	learn: 0.2427761	total: 2.1s	remaining: 3.7s
362:	learn: 0.2423125	total: 2.1s	remaining: 3.69s
363:	learn: 0.2418747	total: 2.11s	remaining: 3.68s
364:	learn: 0.2414956	total: 2.11s	remaining: 3.68s
365:	learn: 0.2410821	total: 2.12s	remaining: 3.67s
366:	learn: 0.2406662	total: 2.13s	remaining: 3.67s
367:	learn: 0.2404660	total: 2.13s	remaining: 3.66s
368:	learn: 0.2402095	total: 2.14s	remaining: 3.65s
369:	learn: 0.2398180	total: 2.14s	remaining: 3.65s
370:	learn: 0.2395792	total: 2.15s	remaining: 3.64s
371:	learn: 0.2392089	total: 2.15s	remaining: 3.63s
372:	learn: 0.2387613	total: 2.16s	remaining: 3.63s
373:	learn: 0.2382645	total: 2.16s	remaining: 3.62s
374:	learn: 0.2379720	total: 2.17s	remaining: 3.62s
375:	learn: 0.2374398	total: 2.17s	remaining: 3.61s
376:	learn: 0.2371097	total: 2.18s	remaining: 3.6s
377:	learn: 0.2366778	total: 2.19s	remaining: 3.6s
378:	learn: 0.2363441	total: 2.19s	remaining: 3.59s
379:	learn: 0.2362081	total: 2.2s	remaining: 3.58s
380:	learn: 0.2355849	total: 2.2s	remaining: 3.58s
381:	learn: 0.2351142	total: 2.21s	remaining: 3.57s
382:	learn: 0.2347887	total: 2.21s	remaining: 3.56s
383:	learn: 0.2345702	total: 2.22s	remaining: 3.56s
384:	learn: 0.2342139	total: 2.22s	remaining: 3.55s
385:	learn: 0.2338097	total: 2.23s	remaining: 3.54s
386:	learn: 0.2333465	total: 2.23s	remaining: 3.54s

In [20]:
from sklearn.svm import SVC

ss = StandardScaler()
X_ss = ss.fit_transform(X)
clf = SVC(random_state=1998, kernel='rbf')
scores = cross_val_score(clf, X_ss, y, cv=kfold, scoring = 'roc_auc')
accu = cross_val_score(clf, X_ss, y, cv=kfold, scoring = 'accuracy')
#print(scores)
print(scores.mean())
print(accu.mean())

0.8788306222397132
0.8063998190863864

# 4. Feature selection

## 4.1 Model-based wrapper method  
Descriptors are iteratively removed based on the feature importance scores obtained from the CatBoost algorithm, and an ML model is subsequently trained using the remaining descriptors at each step

In [23]:
cab = CatBoostClassifier(random_state=1998) 
model = cab.fit(X, y)

Learning rate set to 0.008633
0:	learn: 0.6885815	total: 96.5ms	remaining: 1m 36s
1:	learn: 0.6842017	total: 105ms	remaining: 52.2s
2:	learn: 0.6795803	total: 113ms	remaining: 37.4s
3:	learn: 0.6736846	total: 120ms	remaining: 29.9s
4:	learn: 0.6694115	total: 127ms	remaining: 25.4s
5:	learn: 0.6654192	total: 135ms	remaining: 22.4s
6:	learn: 0.6606206	total: 143ms	remaining: 20.2s
7:	learn: 0.6555866	total: 150ms	remaining: 18.7s
8:	learn: 0.6515120	total: 158ms	remaining: 17.4s
9:	learn: 0.6478855	total: 166ms	remaining: 16.4s
10:	learn: 0.6428744	total: 173ms	remaining: 15.5s
11:	learn: 0.6393260	total: 180ms	remaining: 14.8s
12:	learn: 0.6358441	total: 186ms	remaining: 14.2s
13:	learn: 0.6309978	total: 194ms	remaining: 13.7s
14:	learn: 0.6269680	total: 201ms	remaining: 13.2s
15:	learn: 0.6231725	total: 207ms	remaining: 12.7s
16:	learn: 0.6192011	total: 214ms	remaining: 12.4s
17:	learn: 0.6154941	total: 221ms	remaining: 12s
18:	learn: 0.6121480	total: 228ms	remaining: 11.7s
19:	learn: 0.6078660	total: 234ms	remaining: 11.5s
20:	learn: 0.6033346	total: 241ms	remaining: 11.3s
21:	learn: 0.6000561	total: 248ms	remaining: 11s
22:	learn: 0.5965645	total: 255ms	remaining: 10.8s
23:	learn: 0.5922729	total: 261ms	remaining: 10.6s
24:	learn: 0.5890473	total: 268ms	remaining: 10.4s
25:	learn: 0.5850098	total: 274ms	remaining: 10.3s
26:	learn: 0.5817456	total: 280ms	remaining: 10.1s
27:	learn: 0.5783034	total: 287ms	remaining: 9.96s
28:	learn: 0.5756219	total: 294ms	remaining: 9.83s
29:	learn: 0.5722272	total: 300ms	remaining: 9.7s
30:	learn: 0.5691272	total: 306ms	remaining: 9.57s
31:	learn: 0.5653664	total: 312ms	remaining: 9.44s
32:	learn: 0.5626554	total: 318ms	remaining: 9.33s
33:	learn: 0.5594886	total: 324ms	remaining: 9.22s
34:	learn: 0.5569024	total: 330ms	remaining: 9.11s
35:	learn: 0.5545292	total: 336ms	remaining: 9.01s
36:	learn: 0.5508508	total: 343ms	remaining: 8.92s
37:	learn: 0.5484017	total: 349ms	remaining: 8.84s
38:	learn: 0.5455783	total: 356ms	remaining: 8.76s
39:	learn: 0.5423118	total: 362ms	remaining: 8.7s
40:	learn: 0.5394989	total: 368ms	remaining: 8.61s
41:	learn: 0.5361245	total: 375ms	remaining: 8.55s
42:	learn: 0.5335427	total: 381ms	remaining: 8.48s
43:	learn: 0.5314094	total: 387ms	remaining: 8.41s
44:	learn: 0.5292689	total: 393ms	remaining: 8.35s
45:	learn: 0.5268269	total: 400ms	remaining: 8.29s
46:	learn: 0.5249612	total: 407ms	remaining: 8.25s
47:	learn: 0.5221776	total: 413ms	remaining: 8.2s
48:	learn: 0.5193181	total: 419ms	remaining: 8.14s
49:	learn: 0.5172605	total: 426ms	remaining: 8.09s
50:	learn: 0.5143393	total: 432ms	remaining: 8.04s
51:	learn: 0.5115466	total: 438ms	remaining: 7.99s
52:	learn: 0.5096726	total: 445ms	remaining: 7.95s
53:	learn: 0.5077744	total: 451ms	remaining: 7.9s
54:	learn: 0.5049480	total: 457ms	remaining: 7.85s
55:	learn: 0.5029339	total: 463ms	remaining: 7.8s
56:	learn: 0.5003221	total: 469ms	remaining: 7.76s
57:	learn: 0.4977015	total: 475ms	remaining: 7.72s
58:	learn: 0.4956714	total: 482ms	remaining: 7.69s
59:	learn: 0.4933749	total: 488ms	remaining: 7.64s
60:	learn: 0.4915859	total: 494ms	remaining: 7.6s
61:	learn: 0.4901743	total: 500ms	remaining: 7.57s
62:	learn: 0.4878957	total: 506ms	remaining: 7.53s
63:	learn: 0.4852300	total: 512ms	remaining: 7.5s
64:	learn: 0.4831975	total: 519ms	remaining: 7.46s
65:	learn: 0.4814086	total: 525ms	remaining: 7.43s
66:	learn: 0.4796844	total: 531ms	remaining: 7.39s
67:	learn: 0.4776779	total: 538ms	remaining: 7.37s
68:	learn: 0.4755196	total: 544ms	remaining: 7.34s
69:	learn: 0.4729834	total: 550ms	remaining: 7.31s
70:	learn: 0.4714220	total: 557ms	remaining: 7.28s
71:	learn: 0.4700921	total: 563ms	remaining: 7.25s
72:	learn: 0.4685697	total: 569ms	remaining: 7.23s
73:	learn: 0.4664653	total: 576ms	remaining: 7.2s
74:	learn: 0.4645860	total: 583ms	remaining: 7.18s
75:	learn: 0.4625360	total: 589ms	remaining: 7.16s
76:	learn: 0.4602659	total: 596ms	remaining: 7.15s
77:	learn: 0.4582493	total: 604ms	remaining: 7.14s
78:	learn: 0.4566337	total: 610ms	remaining: 7.11s
79:	learn: 0.4549116	total: 616ms	remaining: 7.09s
80:	learn: 0.4533693	total: 623ms	remaining: 7.07s
81:	learn: 0.4518920	total: 629ms	remaining: 7.05s
82:	learn: 0.4499011	total: 636ms	remaining: 7.03s
83:	learn: 0.4480605	total: 642ms	remaining: 7s
84:	learn: 0.4467473	total: 648ms	remaining: 6.98s
85:	learn: 0.4447305	total: 655ms	remaining: 6.96s
86:	learn: 0.4428639	total: 662ms	remaining: 6.95s
87:	learn: 0.4407485	total: 668ms	remaining: 6.93s
88:	learn: 0.4391804	total: 675ms	remaining: 6.91s
89:	learn: 0.4377526	total: 681ms	remaining: 6.89s
90:	learn: 0.4363458	total: 688ms	remaining: 6.87s
91:	learn: 0.4345298	total: 694ms	remaining: 6.85s
92:	learn: 0.4331044	total: 701ms	remaining: 6.83s
93:	learn: 0.4315225	total: 707ms	remaining: 6.82s
94:	learn: 0.4301792	total: 714ms	remaining: 6.8s
95:	learn: 0.4286394	total: 720ms	remaining: 6.78s
96:	learn: 0.4270203	total: 726ms	remaining: 6.76s
97:	learn: 0.4257681	total: 733ms	remaining: 6.75s
98:	learn: 0.4238133	total: 740ms	remaining: 6.73s
99:	learn: 0.4224635	total: 747ms	remaining: 6.72s
100:	learn: 0.4214239	total: 753ms	remaining: 6.7s
101:	learn: 0.4199325	total: 760ms	remaining: 6.69s
102:	learn: 0.4184515	total: 766ms	remaining: 6.67s
103:	learn: 0.4172054	total: 772ms	remaining: 6.65s
104:	learn: 0.4159292	total: 779ms	remaining: 6.64s
105:	learn: 0.4146296	total: 785ms	remaining: 6.62s
106:	learn: 0.4139477	total: 792ms	remaining: 6.61s
107:	learn: 0.4124447	total: 798ms	remaining: 6.59s
108:	learn: 0.4113406	total: 806ms	remaining: 6.59s
109:	learn: 0.4101809	total: 813ms	remaining: 6.58s
110:	learn: 0.4089587	total: 819ms	remaining: 6.56s
111:	learn: 0.4077125	total: 826ms	remaining: 6.55s
112:	learn: 0.4061915	total: 833ms	remaining: 6.54s
113:	learn: 0.4047013	total: 839ms	remaining: 6.52s
114:	learn: 0.4033271	total: 846ms	remaining: 6.51s
115:	learn: 0.4022567	total: 852ms	remaining: 6.5s
116:	learn: 0.4009551	total: 859ms	remaining: 6.49s
117:	learn: 0.3999670	total: 866ms	remaining: 6.47s
118:	learn: 0.3986395	total: 872ms	remaining: 6.46s
119:	learn: 0.3974798	total: 879ms	remaining: 6.44s
120:	learn: 0.3962286	total: 885ms	remaining: 6.43s
121:	learn: 0.3953859	total: 891ms	remaining: 6.41s
122:	learn: 0.3943377	total: 898ms	remaining: 6.4s
123:	learn: 0.3929525	total: 904ms	remaining: 6.39s
124:	learn: 0.3915769	total: 911ms	remaining: 6.37s
125:	learn: 0.3906860	total: 916ms	remaining: 6.35s
126:	learn: 0.3893927	total: 923ms	remaining: 6.34s
127:	learn: 0.3885700	total: 929ms	remaining: 6.33s
128:	learn: 0.3877155	total: 935ms	remaining: 6.32s
129:	learn: 0.3864762	total: 941ms	remaining: 6.3s
130:	learn: 0.3855701	total: 948ms	remaining: 6.29s
131:	learn: 0.3845028	total: 954ms	remaining: 6.27s
132:	learn: 0.3834447	total: 960ms	remaining: 6.25s
133:	learn: 0.3823527	total: 965ms	remaining: 6.23s
134:	learn: 0.3809626	total: 971ms	remaining: 6.22s
135:	learn: 0.3798225	total: 976ms	remaining: 6.2s
136:	learn: 0.3790973	total: 983ms	remaining: 6.19s
137:	learn: 0.3785318	total: 988ms	remaining: 6.17s
138:	learn: 0.3776727	total: 994ms	remaining: 6.16s
139:	learn: 0.3765317	total: 1000ms	remaining: 6.14s
140:	learn: 0.3756602	total: 1.01s	remaining: 6.13s
141:	learn: 0.3746866	total: 1.01s	remaining: 6.12s
142:	learn: 0.3737639	total: 1.02s	remaining: 6.1s
143:	learn: 0.3729089	total: 1.02s	remaining: 6.09s
144:	learn: 0.3720575	total: 1.03s	remaining: 6.07s
145:	learn: 0.3712899	total: 1.03s	remaining: 6.05s
146:	learn: 0.3702925	total: 1.04s	remaining: 6.04s
147:	learn: 0.3695742	total: 1.05s	remaining: 6.03s
148:	learn: 0.3687634	total: 1.05s	remaining: 6.01s
149:	learn: 0.3679638	total: 1.06s	remaining: 6s
150:	learn: 0.3670726	total: 1.06s	remaining: 5.99s
151:	learn: 0.3659628	total: 1.07s	remaining: 5.97s
152:	learn: 0.3651655	total: 1.07s	remaining: 5.96s
153:	learn: 0.3646093	total: 1.08s	remaining: 5.94s
154:	learn: 0.3635119	total: 1.09s	remaining: 5.92s
155:	learn: 0.3624326	total: 1.09s	remaining: 5.91s
156:	learn: 0.3616391	total: 1.1s	remaining: 5.89s
157:	learn: 0.3608743	total: 1.1s	remaining: 5.88s
158:	learn: 0.3598093	total: 1.11s	remaining: 5.87s
159:	learn: 0.3589023	total: 1.11s	remaining: 5.86s
160:	learn: 0.3582743	total: 1.12s	remaining: 5.84s
161:	learn: 0.3571635	total: 1.13s	remaining: 5.83s
162:	learn: 0.3563086	total: 1.13s	remaining: 5.82s
163:	learn: 0.3552929	total: 1.14s	remaining: 5.8s
164:	learn: 0.3544064	total: 1.14s	remaining: 5.79s
165:	learn: 0.3539441	total: 1.15s	remaining: 5.77s
166:	learn: 0.3530207	total: 1.16s	remaining: 5.76s
167:	learn: 0.3521338	total: 1.16s	remaining: 5.75s
168:	learn: 0.3512640	total: 1.17s	remaining: 5.74s
169:	learn: 0.3506346	total: 1.17s	remaining: 5.72s
170:	learn: 0.3498148	total: 1.18s	remaining: 5.71s
171:	learn: 0.3492491	total: 1.18s	remaining: 5.7s
172:	learn: 0.3484675	total: 1.19s	remaining: 5.69s
173:	learn: 0.3480636	total: 1.19s	remaining: 5.67s
174:	learn: 0.3471177	total: 1.2s	remaining: 5.66s
175:	learn: 0.3465000	total: 1.21s	remaining: 5.65s
176:	learn: 0.3458110	total: 1.21s	remaining: 5.64s
177:	learn: 0.3449477	total: 1.22s	remaining: 5.63s
178:	learn: 0.3442422	total: 1.22s	remaining: 5.62s
179:	learn: 0.3431450	total: 1.23s	remaining: 5.61s
180:	learn: 0.3424612	total: 1.24s	remaining: 5.6s
181:	learn: 0.3416170	total: 1.24s	remaining: 5.58s
182:	learn: 0.3407794	total: 1.25s	remaining: 5.57s
183:	learn: 0.3402322	total: 1.25s	remaining: 5.56s
184:	learn: 0.3394623	total: 1.26s	remaining: 5.55s
185:	learn: 0.3389827	total: 1.26s	remaining: 5.54s
186:	learn: 0.3382561	total: 1.27s	remaining: 5.52s
187:	learn: 0.3373820	total: 1.28s	remaining: 5.51s
188:	learn: 0.3367866	total: 1.28s	remaining: 5.5s
189:	learn: 0.3361142	total: 1.29s	remaining: 5.49s
190:	learn: 0.3353401	total: 1.29s	remaining: 5.49s
191:	learn: 0.3345298	total: 1.3s	remaining: 5.47s
192:	learn: 0.3339021	total: 1.31s	remaining: 5.46s
193:	learn: 0.3332398	total: 1.31s	remaining: 5.45s
194:	learn: 0.3323774	total: 1.32s	remaining: 5.44s
195:	learn: 0.3317505	total: 1.32s	remaining: 5.43s
196:	learn: 0.3310162	total: 1.33s	remaining: 5.42s
197:	learn: 0.3303265	total: 1.34s	remaining: 5.41s
198:	learn: 0.3295568	total: 1.34s	remaining: 5.4s
199:	learn: 0.3289143	total: 1.35s	remaining: 5.39s
200:	learn: 0.3282371	total: 1.35s	remaining: 5.38s
201:	learn: 0.3274254	total: 1.36s	remaining: 5.37s
202:	learn: 0.3265559	total: 1.37s	remaining: 5.36s
203:	learn: 0.3255542	total: 1.37s	remaining: 5.35s
204:	learn: 0.3249929	total: 1.38s	remaining: 5.34s
205:	learn: 0.3244906	total: 1.38s	remaining: 5.34s
206:	learn: 0.3238064	total: 1.39s	remaining: 5.33s
207:	learn: 0.3234018	total: 1.4s	remaining: 5.32s
208:	learn: 0.3227186	total: 1.4s	remaining: 5.31s
209:	learn: 0.3218416	total: 1.41s	remaining: 5.3s
210:	learn: 0.3212196	total: 1.41s	remaining: 5.29s
211:	learn: 0.3205521	total: 1.42s	remaining: 5.28s
212:	learn: 0.3199812	total: 1.43s	remaining: 5.27s
213:	learn: 0.3193241	total: 1.43s	remaining: 5.26s
214:	learn: 0.3186832	total: 1.44s	remaining: 5.25s
215:	learn: 0.3180555	total: 1.44s	remaining: 5.24s
216:	learn: 0.3172330	total: 1.45s	remaining: 5.23s
217:	learn: 0.3167401	total: 1.46s	remaining: 5.22s
218:	learn: 0.3161960	total: 1.46s	remaining: 5.21s
219:	learn: 0.3156510	total: 1.47s	remaining: 5.2s
220:	learn: 0.3150252	total: 1.47s	remaining: 5.19s
221:	learn: 0.3142286	total: 1.48s	remaining: 5.19s
222:	learn: 0.3136732	total: 1.49s	remaining: 5.18s
223:	learn: 0.3130303	total: 1.49s	remaining: 5.17s
224:	learn: 0.3124879	total: 1.5s	remaining: 5.16s
225:	learn: 0.3118590	total: 1.5s	remaining: 5.15s
226:	learn: 0.3112382	total: 1.51s	remaining: 5.14s
227:	learn: 0.3105634	total: 1.51s	remaining: 5.13s
228:	learn: 0.3097647	total: 1.52s	remaining: 5.12s
229:	learn: 0.3094089	total: 1.53s	remaining: 5.11s
230:	learn: 0.3085275	total: 1.53s	remaining: 5.1s
231:	learn: 0.3081681	total: 1.54s	remaining: 5.1s
232:	learn: 0.3075498	total: 1.54s	remaining: 5.09s
233:	learn: 0.3070534	total: 1.55s	remaining: 5.08s
234:	learn: 0.3065818	total: 1.56s	remaining: 5.07s
235:	learn: 0.3058823	total: 1.56s	remaining: 5.06s
236:	learn: 0.3052074	total: 1.57s	remaining: 5.05s
237:	learn: 0.3045929	total: 1.57s	remaining: 5.04s
238:	learn: 0.3039733	total: 1.58s	remaining: 5.03s
239:	learn: 0.3033546	total: 1.59s	remaining: 5.02s
240:	learn: 0.3026868	total: 1.59s	remaining: 5.01s
241:	learn: 0.3018216	total: 1.6s	remaining: 5.01s
242:	learn: 0.3013674	total: 1.6s	remaining: 5s
243:	learn: 0.3008055	total: 1.61s	remaining: 4.99s
244:	learn: 0.3002160	total: 1.62s	remaining: 4.98s
245:	learn: 0.2998118	total: 1.62s	remaining: 4.97s
246:	learn: 0.2992558	total: 1.63s	remaining: 4.96s
247:	learn: 0.2986453	total: 1.63s	remaining: 4.95s
248:	learn: 0.2979561	total: 1.64s	remaining: 4.95s
249:	learn: 0.2973570	total: 1.65s	remaining: 4.94s
250:	learn: 0.2970491	total: 1.65s	remaining: 4.93s
251:	learn: 0.2963265	total: 1.66s	remaining: 4.92s
252:	learn: 0.2956623	total: 1.66s	remaining: 4.91s
253:	learn: 0.2952709	total: 1.67s	remaining: 4.9s
254:	learn: 0.2947345	total: 1.68s	remaining: 4.89s
255:	learn: 0.2941265	total: 1.68s	remaining: 4.89s
256:	learn: 0.2936196	total: 1.69s	remaining: 4.88s
257:	learn: 0.2931775	total: 1.69s	remaining: 4.87s
258:	learn: 0.2924622	total: 1.7s	remaining: 4.86s
259:	learn: 0.2920742	total: 1.71s	remaining: 4.86s
260:	learn: 0.2915691	total: 1.71s	remaining: 4.85s
261:	learn: 0.2908679	total: 1.72s	remaining: 4.84s
262:	learn: 0.2902633	total: 1.72s	remaining: 4.83s
263:	learn: 0.2899489	total: 1.73s	remaining: 4.82s
264:	learn: 0.2896066	total: 1.74s	remaining: 4.81s
265:	learn: 0.2890352	total: 1.74s	remaining: 4.8s
266:	learn: 0.2884810	total: 1.75s	remaining: 4.79s
267:	learn: 0.2881203	total: 1.75s	remaining: 4.79s
268:	learn: 0.2874935	total: 1.76s	remaining: 4.78s
269:	learn: 0.2869322	total: 1.76s	remaining: 4.77s
270:	learn: 0.2864024	total: 1.77s	remaining: 4.77s
271:	learn: 0.2859412	total: 1.78s	remaining: 4.76s
272:	learn: 0.2852646	total: 1.78s	remaining: 4.75s
273:	learn: 0.2847297	total: 1.79s	remaining: 4.74s
274:	learn: 0.2843376	total: 1.79s	remaining: 4.73s
275:	learn: 0.2841170	total: 1.8s	remaining: 4.72s
276:	learn: 0.2837235	total: 1.81s	remaining: 4.71s
277:	learn: 0.2830544	total: 1.81s	remaining: 4.71s
278:	learn: 0.2825895	total: 1.82s	remaining: 4.7s
279:	learn: 0.2821105	total: 1.82s	remaining: 4.69s
280:	learn: 0.2819909	total: 1.83s	remaining: 4.68s
281:	learn: 0.2815780	total: 1.84s	remaining: 4.68s
282:	learn: 0.2810968	total: 1.84s	remaining: 4.67s
283:	learn: 0.2807204	total: 1.85s	remaining: 4.66s
284:	learn: 0.2801404	total: 1.85s	remaining: 4.65s
285:	learn: 0.2797497	total: 1.86s	remaining: 4.64s
286:	learn: 0.2793875	total: 1.86s	remaining: 4.63s
287:	learn: 0.2788918	total: 1.87s	remaining: 4.63s
288:	learn: 0.2785305	total: 1.88s	remaining: 4.62s
289:	learn: 0.2782200	total: 1.88s	remaining: 4.61s
290:	learn: 0.2776640	total: 1.89s	remaining: 4.6s
291:	learn: 0.2771610	total: 1.89s	remaining: 4.59s
292:	learn: 0.2769050	total: 1.9s	remaining: 4.58s
293:	learn: 0.2765391	total: 1.91s	remaining: 4.58s
294:	learn: 0.2761381	total: 1.91s	remaining: 4.57s
295:	learn: 0.2758073	total: 1.92s	remaining: 4.56s
296:	learn: 0.2754055	total: 1.92s	remaining: 4.55s
297:	learn: 0.2749717	total: 1.93s	remaining: 4.54s
298:	learn: 0.2745142	total: 1.93s	remaining: 4.54s
299:	learn: 0.2740117	total: 1.94s	remaining: 4.53s
300:	learn: 0.2736874	total: 1.95s	remaining: 4.52s
301:	learn: 0.2732217	total: 1.95s	remaining: 4.51s
302:	learn: 0.2727505	total: 1.96s	remaining: 4.5s
303:	learn: 0.2724312	total: 1.96s	remaining: 4.49s
304:	learn: 0.2719288	total: 1.97s	remaining: 4.49s
305:	learn: 0.2716576	total: 1.98s	remaining: 4.48s
306:	learn: 0.2714164	total: 1.98s	remaining: 4.47s
307:	learn: 0.2711270	total: 1.99s	remaining: 4.46s
308:	learn: 0.2706849	total: 1.99s	remaining: 4.46s
309:	learn: 0.2702541	total: 2s	remaining: 4.45s
310:	learn: 0.2697310	total: 2s	remaining: 4.44s
311:	learn: 0.2693013	total: 2.01s	remaining: 4.43s
312:	learn: 0.2689990	total: 2.02s	remaining: 4.43s
313:	learn: 0.2687436	total: 2.02s	remaining: 4.42s
314:	learn: 0.2683329	total: 2.03s	remaining: 4.41s
315:	learn: 0.2679899	total: 2.03s	remaining: 4.4s
316:	learn: 0.2677659	total: 2.04s	remaining: 4.39s
317:	learn: 0.2673345	total: 2.05s	remaining: 4.39s
318:	learn: 0.2670475	total: 2.05s	remaining: 4.38s
319:	learn: 0.2666453	total: 2.06s	remaining: 4.37s
320:	learn: 0.2661535	total: 2.06s	remaining: 4.37s
321:	learn: 0.2657484	total: 2.07s	remaining: 4.36s
322:	learn: 0.2653006	total: 2.07s	remaining: 4.35s
323:	learn: 0.2650638	total: 2.08s	remaining: 4.34s
324:	learn: 0.2646944	total: 2.09s	remaining: 4.33s
325:	learn: 0.2642900	total: 2.09s	remaining: 4.33s
326:	learn: 0.2638845	total: 2.1s	remaining: 4.32s
327:	learn: 0.2633602	total: 2.1s	remaining: 4.31s
328:	learn: 0.2631135	total: 2.11s	remaining: 4.3s
329:	learn: 0.2628884	total: 2.12s	remaining: 4.3s
330:	learn: 0.2625830	total: 2.12s	remaining: 4.29s
331:	learn: 0.2623252	total: 2.13s	remaining: 4.28s
332:	learn: 0.2618442	total: 2.13s	remaining: 4.27s
333:	learn: 0.2615298	total: 2.14s	remaining: 4.27s
334:	learn: 0.2610574	total: 2.15s	remaining: 4.26s
335:	learn: 0.2607481	total: 2.15s	remaining: 4.25s
336:	learn: 0.2604338	total: 2.16s	remaining: 4.24s
337:	learn: 0.2600424	total: 2.16s	remaining: 4.24s
338:	learn: 0.2597148	total: 2.17s	remaining: 4.23s
339:	learn: 0.2593972	total: 2.18s	remaining: 4.23s
340:	learn: 0.2592213	total: 2.18s	remaining: 4.22s
341:	learn: 0.2588401	total: 2.19s	remaining: 4.21s
342:	learn: 0.2584448	total: 2.19s	remaining: 4.2s
343:	learn: 0.2583002	total: 2.2s	remaining: 4.2s
344:	learn: 0.2578017	total: 2.21s	remaining: 4.19s
345:	learn: 0.2573749	total: 2.21s	remaining: 4.18s
346:	learn: 0.2570282	total: 2.22s	remaining: 4.18s
347:	learn: 0.2566782	total: 2.23s	remaining: 4.17s
348:	learn: 0.2561972	total: 2.23s	remaining: 4.16s
349:	learn: 0.2557852	total: 2.24s	remaining: 4.15s
350:	learn: 0.2553091	total: 2.24s	remaining: 4.15s
351:	learn: 0.2548053	total: 2.25s	remaining: 4.14s
352:	learn: 0.2544224	total: 2.25s	remaining: 4.13s
353:	learn: 0.2539976	total: 2.26s	remaining: 4.13s
354:	learn: 0.2535402	total: 2.27s	remaining: 4.12s
355:	learn: 0.2532419	total: 2.27s	remaining: 4.11s
356:	learn: 0.2529249	total: 2.28s	remaining: 4.1s
357:	learn: 0.2526440	total: 2.28s	remaining: 4.09s
358:	learn: 0.2522565	total: 2.29s	remaining: 4.09s
359:	learn: 0.2519747	total: 2.29s	remaining: 4.08s
360:	learn: 0.2515233	total: 2.3s	remaining: 4.07s
361:	learn: 0.2512170	total: 2.31s	remaining: 4.07s
362:	learn: 0.2507229	total: 2.31s	remaining: 4.06s
363:	learn: 0.2504430	total: 2.32s	remaining: 4.05s
364:	learn: 0.2500717	total: 2.32s	remaining: 4.04s
365:	learn: 0.2497088	total: 2.33s	remaining: 4.03s
366:	learn: 0.2493884	total: 2.33s	remaining: 4.03s
367:	learn: 0.2490819	total: 2.34s	remaining: 4.02s
368:	learn: 0.2488426	total: 2.35s	remaining: 4.01s
369:	learn: 0.2485921	total: 2.35s	remaining: 4s
370:	learn: 0.2483031	total: 2.36s	remaining: 4s
371:	learn: 0.2479344	total: 2.36s	remaining: 3.99s
372:	learn: 0.2476209	total: 2.37s	remaining: 3.98s
373:	learn: 0.2473325	total: 2.38s	remaining: 3.98s
374:	learn: 0.2470617	total: 2.38s	remaining: 3.97s
375:	learn: 0.2465725	total: 2.39s	remaining: 3.96s
376:	learn: 0.2461013	total: 2.4s	remaining: 3.96s
377:	learn: 0.2457972	total: 2.4s	remaining: 3.95s
378:	learn: 0.2454700	total: 2.41s	remaining: 3.95s
379:	learn: 0.2452003	total: 2.42s	remaining: 3.94s
380:	learn: 0.2449135	total: 2.42s	remaining: 3.94s
381:	learn: 0.2447508	total: 2.43s	remaining: 3.93s
382:	learn: 0.2443363	total: 2.43s	remaining: 3.92s
383:	learn: 0.2439900	total: 2.44s	remaining: 3.91s
384:	learn: 0.2436971	total: 2.44s	remaining: 3.91s
385:	learn: 0.2431416	total: 2.45s	remaining: 3.9s
386:	learn: 0.2426088	total: 2.46s	remaining: 3.89s

### Save the feature importance

In [26]:
Bset = pd.DataFrame()
Bset['feature'] = X.columns
Bset['importance'] = model.feature_importances_
Bset = Bset.sort_values(by='importance', ascending=False)
Bset.reset_index(drop=True, inplace=True)
Bset

                                    feature  importance
0       minimum neighbor distance variation    2.396339
1           MagpieData minimum AtomicWeight    1.853504
2                    max packing efficiency    1.716766
3         MagpieData maximum CovalentRadius    1.695726
4                    MagpieData mean Number    1.393513
..                                      ...         ...
268            MagpieData minimum NpValence    0.000000
269            MagpieData minimum GSbandgap    0.000000
270           MagpieData minimum NpUnfilled    0.000000
271  minimum local difference in NfUnfilled    0.000000
272            MagpieData maximum NsValence    0.000000

[273 rows x 2 columns]

Considering that writing a for loop and running it once may cause CatBoost memory overflow, it is recommended to run it step by step

In [28]:
selected_features = Bset['feature'].head(11).tolist()
X_selected = X[selected_features]

clf = CatBoostClassifier(random_state=1998)
scores = cross_val_score(clf, X_selected, y, cv=kfold, scoring = 'roc_auc')
roc_mean = np.mean(scores)

print(f'ten-fold scores: ROC_mean={roc_mean:.2f}')

Learning rate set to 0.008248
0:	learn: 0.6876764	total: 6.16ms	remaining: 6.15s
1:	learn: 0.6827019	total: 9.81ms	remaining: 4.9s
2:	learn: 0.6768219	total: 13ms	remaining: 4.32s
3:	learn: 0.6718565	total: 16ms	remaining: 4s
4:	learn: 0.6664216	total: 18.9ms	remaining: 3.77s
5:	learn: 0.6612231	total: 21.6ms	remaining: 3.58s
6:	learn: 0.6569157	total: 24.3ms	remaining: 3.44s
7:	learn: 0.6527366	total: 27ms	remaining: 3.34s
8:	learn: 0.6483948	total: 29.7ms	remaining: 3.27s
9:	learn: 0.6435155	total: 32.4ms	remaining: 3.21s
10:	learn: 0.6393926	total: 35.1ms	remaining: 3.15s
11:	learn: 0.6347297	total: 37.7ms	remaining: 3.1s
12:	learn: 0.6306701	total: 40.2ms	remaining: 3.05s
13:	learn: 0.6262482	total: 42.8ms	remaining: 3.01s
14:	learn: 0.6213852	total: 45.3ms	remaining: 2.98s
15:	learn: 0.6179424	total: 47.8ms	remaining: 2.94s
16:	learn: 0.6136588	total: 50ms	remaining: 2.89s
17:	learn: 0.6097412	total: 52.4ms	remaining: 2.86s
18:	learn: 0.6056145	total: 54.6ms	remaining: 2.82s
19:	learn: 0.6022085	total: 57ms	remaining: 2.79s
20:	learn: 0.5981019	total: 59.3ms	remaining: 2.77s
21:	learn: 0.5945657	total: 61.6ms	remaining: 2.74s
22:	learn: 0.5910407	total: 64.1ms	remaining: 2.72s
23:	learn: 0.5878218	total: 66.4ms	remaining: 2.7s
24:	learn: 0.5847248	total: 68.5ms	remaining: 2.67s
25:	learn: 0.5809950	total: 70.8ms	remaining: 2.65s
26:	learn: 0.5775429	total: 73ms	remaining: 2.63s
27:	learn: 0.5740673	total: 75.2ms	remaining: 2.61s
28:	learn: 0.5713847	total: 77.6ms	remaining: 2.6s
29:	learn: 0.5682721	total: 80.1ms	remaining: 2.59s
30:	learn: 0.5658581	total: 82.2ms	remaining: 2.57s
31:	learn: 0.5623129	total: 84.3ms	remaining: 2.55s
32:	learn: 0.5593720	total: 86.5ms	remaining: 2.53s
33:	learn: 0.5556932	total: 88.6ms	remaining: 2.52s
34:	learn: 0.5525189	total: 90.6ms	remaining: 2.5s
35:	learn: 0.5496740	total: 92.7ms	remaining: 2.48s
36:	learn: 0.5463784	total: 94.8ms	remaining: 2.47s
37:	learn: 0.5435093	total: 96.9ms	remaining: 2.45s
38:	learn: 0.5412410	total: 99ms	remaining: 2.44s
39:	learn: 0.5378171	total: 101ms	remaining: 2.42s
40:	learn: 0.5347918	total: 103ms	remaining: 2.41s
41:	learn: 0.5311744	total: 105ms	remaining: 2.39s
42:	learn: 0.5288445	total: 107ms	remaining: 2.38s
43:	learn: 0.5267108	total: 109ms	remaining: 2.36s
44:	learn: 0.5235337	total: 111ms	remaining: 2.35s
45:	learn: 0.5206111	total: 112ms	remaining: 2.33s
46:	learn: 0.5183945	total: 114ms	remaining: 2.31s
47:	learn: 0.5156011	total: 116ms	remaining: 2.3s
48:	learn: 0.5129754	total: 118ms	remaining: 2.28s
49:	learn: 0.5100765	total: 119ms	remaining: 2.27s
50:	learn: 0.5079752	total: 121ms	remaining: 2.25s
51:	learn: 0.5055434	total: 123ms	remaining: 2.24s
52:	learn: 0.5035591	total: 124ms	remaining: 2.22s
53:	learn: 0.5009664	total: 126ms	remaining: 2.21s
54:	learn: 0.4990193	total: 128ms	remaining: 2.19s
55:	learn: 0.4972540	total: 129ms	remaining: 2.18s
56:	learn: 0.4952926	total: 131ms	remaining: 2.17s
57:	learn: 0.4934003	total: 133ms	remaining: 2.15s
58:	learn: 0.4917468	total: 134ms	remaining: 2.14s
59:	learn: 0.4898675	total: 136ms	remaining: 2.13s
60:	learn: 0.4877354	total: 138ms	remaining: 2.12s
61:	learn: 0.4857616	total: 139ms	remaining: 2.11s
62:	learn: 0.4835642	total: 141ms	remaining: 2.1s
63:	learn: 0.4813917	total: 143ms	remaining: 2.09s
64:	learn: 0.4795246	total: 144ms	remaining: 2.08s
65:	learn: 0.4773230	total: 146ms	remaining: 2.07s
66:	learn: 0.4757981	total: 148ms	remaining: 2.06s
67:	learn: 0.4735780	total: 149ms	remaining: 2.05s
68:	learn: 0.4713042	total: 151ms	remaining: 2.04s
69:	learn: 0.4697260	total: 153ms	remaining: 2.03s
70:	learn: 0.4680789	total: 154ms	remaining: 2.02s
71:	learn: 0.4660407	total: 156ms	remaining: 2.01s
72:	learn: 0.4639495	total: 157ms	remaining: 2s
73:	learn: 0.4619525	total: 159ms	remaining: 1.99s
74:	learn: 0.4601356	total: 161ms	remaining: 1.98s
75:	learn: 0.4588123	total: 162ms	remaining: 1.97s
76:	learn: 0.4571162	total: 164ms	remaining: 1.96s
77:	learn: 0.4554089	total: 166ms	remaining: 1.96s
78:	learn: 0.4538924	total: 167ms	remaining: 1.95s
79:	learn: 0.4527393	total: 169ms	remaining: 1.94s
80:	learn: 0.4514640	total: 170ms	remaining: 1.93s
81:	learn: 0.4498350	total: 172ms	remaining: 1.92s
82:	learn: 0.4483088	total: 173ms	remaining: 1.91s
83:	learn: 0.4469899	total: 175ms	remaining: 1.9s
84:	learn: 0.4454853	total: 176ms	remaining: 1.9s
85:	learn: 0.4443155	total: 178ms	remaining: 1.89s
86:	learn: 0.4430093	total: 179ms	remaining: 1.88s
87:	learn: 0.4413237	total: 181ms	remaining: 1.87s
88:	learn: 0.4401492	total: 182ms	remaining: 1.86s
89:	learn: 0.4388313	total: 184ms	remaining: 1.86s
90:	learn: 0.4375839	total: 185ms	remaining: 1.85s
91:	learn: 0.4362923	total: 186ms	remaining: 1.84s
92:	learn: 0.4349213	total: 188ms	remaining: 1.83s
93:	learn: 0.4334284	total: 189ms	remaining: 1.82s
94:	learn: 0.4321752	total: 191ms	remaining: 1.82s
95:	learn: 0.4309820	total: 193ms	remaining: 1.82s
96:	learn: 0.4296494	total: 194ms	remaining: 1.81s
97:	learn: 0.4281227	total: 196ms	remaining: 1.8s
98:	learn: 0.4269924	total: 197ms	remaining: 1.79s
99:	learn: 0.4258594	total: 199ms	remaining: 1.79s
100:	learn: 0.4245634	total: 200ms	remaining: 1.78s
101:	learn: 0.4233191	total: 202ms	remaining: 1.77s
102:	learn: 0.4222477	total: 203ms	remaining: 1.77s
103:	learn: 0.4211841	total: 204ms	remaining: 1.76s
104:	learn: 0.4196059	total: 206ms	remaining: 1.75s
105:	learn: 0.4183872	total: 207ms	remaining: 1.75s
106:	learn: 0.4172784	total: 209ms	remaining: 1.74s
107:	learn: 0.4161284	total: 210ms	remaining: 1.74s
108:	learn: 0.4152257	total: 212ms	remaining: 1.73s
109:	learn: 0.4142827	total: 213ms	remaining: 1.73s
110:	learn: 0.4129970	total: 215ms	remaining: 1.72s
111:	learn: 0.4117620	total: 216ms	remaining: 1.71s
112:	learn: 0.4103271	total: 218ms	remaining: 1.71s
113:	learn: 0.4090902	total: 219ms	remaining: 1.7s
114:	learn: 0.4080819	total: 221ms	remaining: 1.7s
115:	learn: 0.4068119	total: 222ms	remaining: 1.69s
116:	learn: 0.4056519	total: 223ms	remaining: 1.69s
117:	learn: 0.4047232	total: 225ms	remaining: 1.68s
118:	learn: 0.4035420	total: 226ms	remaining: 1.68s
119:	learn: 0.4022380	total: 228ms	remaining: 1.67s
120:	learn: 0.4013554	total: 229ms	remaining: 1.66s
121:	learn: 0.4000772	total: 231ms	remaining: 1.66s
122:	learn: 0.3990465	total: 232ms	remaining: 1.65s
123:	learn: 0.3980736	total: 234ms	remaining: 1.65s
124:	learn: 0.3974360	total: 235ms	remaining: 1.64s
125:	learn: 0.3964566	total: 236ms	remaining: 1.64s
126:	learn: 0.3953886	total: 238ms	remaining: 1.64s
127:	learn: 0.3942912	total: 239ms	remaining: 1.63s
128:	learn: 0.3934493	total: 241ms	remaining: 1.63s
129:	learn: 0.3920252	total: 242ms	remaining: 1.62s
130:	learn: 0.3911338	total: 244ms	remaining: 1.62s
131:	learn: 0.3902352	total: 245ms	remaining: 1.61s
132:	learn: 0.3893873	total: 247ms	remaining: 1.61s
133:	learn: 0.3885812	total: 248ms	remaining: 1.6s
134:	learn: 0.3875897	total: 250ms	remaining: 1.6s
135:	learn: 0.3867491	total: 251ms	remaining: 1.59s
136:	learn: 0.3857326	total: 252ms	remaining: 1.59s
137:	learn: 0.3852631	total: 254ms	remaining: 1.58s
138:	learn: 0.3845033	total: 255ms	remaining: 1.58s
139:	learn: 0.3834253	total: 257ms	remaining: 1.58s
140:	learn: 0.3824892	total: 258ms	remaining: 1.57s
141:	learn: 0.3818940	total: 260ms	remaining: 1.57s
142:	learn: 0.3810409	total: 261ms	remaining: 1.56s
143:	learn: 0.3803034	total: 262ms	remaining: 1.56s
144:	learn: 0.3796371	total: 264ms	remaining: 1.56s
145:	learn: 0.3784934	total: 265ms	remaining: 1.55s
146:	learn: 0.3775135	total: 267ms	remaining: 1.55s
147:	learn: 0.3767567	total: 268ms	remaining: 1.54s
148:	learn: 0.3761509	total: 270ms	remaining: 1.54s
149:	learn: 0.3753836	total: 271ms	remaining: 1.54s
150:	learn: 0.3746388	total: 273ms	remaining: 1.53s
151:	learn: 0.3735678	total: 274ms	remaining: 1.53s
152:	learn: 0.3728324	total: 276ms	remaining: 1.53s
153:	learn: 0.3721216	total: 277ms	remaining: 1.52s
154:	learn: 0.3714014	total: 279ms	remaining: 1.52s
155:	learn: 0.3706969	total: 280ms	remaining: 1.51s
156:	learn: 0.3700979	total: 281ms	remaining: 1.51s
157:	learn: 0.3693867	total: 283ms	remaining: 1.51s
158:	learn: 0.3687127	total: 284ms	remaining: 1.5s
159:	learn: 0.3680719	total: 286ms	remaining: 1.5s
160:	learn: 0.3675633	total: 287ms	remaining: 1.5s
161:	learn: 0.3669808	total: 289ms	remaining: 1.49s
162:	learn: 0.3662601	total: 290ms	remaining: 1.49s
163:	learn: 0.3653989	total: 292ms	remaining: 1.49s
164:	learn: 0.3646803	total: 293ms	remaining: 1.48s
165:	learn: 0.3638755	total: 295ms	remaining: 1.48s
166:	learn: 0.3630106	total: 296ms	remaining: 1.48s
167:	learn: 0.3622866	total: 297ms	remaining: 1.47s
168:	learn: 0.3615380	total: 299ms	remaining: 1.47s
169:	learn: 0.3607955	total: 300ms	remaining: 1.47s
170:	learn: 0.3600419	total: 302ms	remaining: 1.46s
171:	learn: 0.3593512	total: 303ms	remaining: 1.46s
172:	learn: 0.3589593	total: 305ms	remaining: 1.46s
173:	learn: 0.3582773	total: 306ms	remaining: 1.45s
174:	learn: 0.3577523	total: 308ms	remaining: 1.45s
175:	learn: 0.3572194	total: 309ms	remaining: 1.45s
176:	learn: 0.3562775	total: 311ms	remaining: 1.44s
177:	learn: 0.3553837	total: 312ms	remaining: 1.44s
178:	learn: 0.3547125	total: 314ms	remaining: 1.44s
179:	learn: 0.3542163	total: 315ms	remaining: 1.43s
180:	learn: 0.3533209	total: 316ms	remaining: 1.43s
181:	learn: 0.3528064	total: 318ms	remaining: 1.43s
182:	learn: 0.3521884	total: 319ms	remaining: 1.43s
183:	learn: 0.3514397	total: 321ms	remaining: 1.42s
184:	learn: 0.3509894	total: 322ms	remaining: 1.42s
185:	learn: 0.3504462	total: 324ms	remaining: 1.42s
186:	learn: 0.3498252	total: 325ms	remaining: 1.41s
187:	learn: 0.3493462	total: 327ms	remaining: 1.41s
188:	learn: 0.3485161	total: 328ms	remaining: 1.41s
189:	learn: 0.3480343	total: 329ms	remaining: 1.4s
190:	learn: 0.3473594	total: 331ms	remaining: 1.4s
191:	learn: 0.3468295	total: 332ms	remaining: 1.4s
192:	learn: 0.3460027	total: 334ms	remaining: 1.4s
193:	learn: 0.3453077	total: 335ms	remaining: 1.39s
194:	learn: 0.3445495	total: 337ms	remaining: 1.39s
195:	learn: 0.3439784	total: 338ms	remaining: 1.39s
196:	learn: 0.3431843	total: 340ms	remaining: 1.38s
197:	learn: 0.3427946	total: 341ms	remaining: 1.38s
198:	learn: 0.3422629	total: 343ms	remaining: 1.38s
199:	learn: 0.3416508	total: 344ms	remaining: 1.38s
200:	learn: 0.3409103	total: 345ms	remaining: 1.37s
201:	learn: 0.3400971	total: 347ms	remaining: 1.37s
202:	learn: 0.3395242	total: 348ms	remaining: 1.37s
203:	learn: 0.3388925	total: 350ms	remaining: 1.36s
204:	learn: 0.3383166	total: 351ms	remaining: 1.36s
205:	learn: 0.3377596	total: 353ms	remaining: 1.36s
206:	learn: 0.3368710	total: 354ms	remaining: 1.36s
207:	learn: 0.3364230	total: 356ms	remaining: 1.35s
208:	learn: 0.3357337	total: 357ms	remaining: 1.35s
209:	learn: 0.3351526	total: 359ms	remaining: 1.35s
210:	learn: 0.3346339	total: 360ms	remaining: 1.35s
211:	learn: 0.3341133	total: 361ms	remaining: 1.34s
212:	learn: 0.3336764	total: 363ms	remaining: 1.34s
213:	learn: 0.3331516	total: 364ms	remaining: 1.34s
214:	learn: 0.3326465	total: 366ms	remaining: 1.33s
215:	learn: 0.3321061	total: 367ms	remaining: 1.33s
216:	learn: 0.3314523	total: 369ms	remaining: 1.33s
217:	learn: 0.3307705	total: 370ms	remaining: 1.33s
218:	learn: 0.3302275	total: 371ms	remaining: 1.32s
219:	learn: 0.3295569	total: 373ms	remaining: 1.32s
220:	learn: 0.3292217	total: 374ms	remaining: 1.32s
221:	learn: 0.3285308	total: 376ms	remaining: 1.32s
222:	learn: 0.3284597	total: 376ms	remaining: 1.31s
223:	learn: 0.3278948	total: 378ms	remaining: 1.31s
224:	learn: 0.3273884	total: 379ms	remaining: 1.3s
225:	learn: 0.3269738	total: 380ms	remaining: 1.3s
226:	learn: 0.3262651	total: 382ms	remaining: 1.3s
227:	learn: 0.3258156	total: 384ms	remaining: 1.3s
228:	learn: 0.3249986	total: 385ms	remaining: 1.3s
229:	learn: 0.3245130	total: 387ms	remaining: 1.29s
230:	learn: 0.3238980	total: 388ms	remaining: 1.29s
231:	learn: 0.3234353	total: 390ms	remaining: 1.29s
232:	learn: 0.3230265	total: 391ms	remaining: 1.29s
233:	learn: 0.3223739	total: 393ms	remaining: 1.28s
234:	learn: 0.3219352	total: 394ms	remaining: 1.28s
235:	learn: 0.3215853	total: 396ms	remaining: 1.28s
236:	learn: 0.3210125	total: 397ms	remaining: 1.28s
237:	learn: 0.3203656	total: 398ms	remaining: 1.27s
238:	learn: 0.3199933	total: 400ms	remaining: 1.27s
239:	learn: 0.3193722	total: 401ms	remaining: 1.27s
240:	learn: 0.3189621	total: 403ms	remaining: 1.27s
241:	learn: 0.3185211	total: 404ms	remaining: 1.27s
242:	learn: 0.3181239	total: 406ms	remaining: 1.26s
243:	learn: 0.3173786	total: 407ms	remaining: 1.26s
244:	learn: 0.3169468	total: 409ms	remaining: 1.26s
245:	learn: 0.3163475	total: 410ms	remaining: 1.26s
246:	learn: 0.3157675	total: 412ms	remaining: 1.25s
247:	learn: 0.3152307	total: 413ms	remaining: 1.25s
248:	learn: 0.3147815	total: 414ms	remaining: 1.25s
249:	learn: 0.3143457	total: 416ms	remaining: 1.25s
250:	learn: 0.3136772	total: 417ms	remaining: 1.24s
251:	learn: 0.3133440	total: 419ms	remaining: 1.24s
252:	learn: 0.3130284	total: 420ms	remaining: 1.24s
253:	learn: 0.3125947	total: 422ms	remaining: 1.24s
254:	learn: 0.3120243	total: 424ms	remaining: 1.24s
255:	learn: 0.3113786	total: 425ms	remaining: 1.24s
256:	learn: 0.3111765	total: 427ms	remaining: 1.23s
257:	learn: 0.3106042	total: 429ms	remaining: 1.23s
258:	learn: 0.3102571	total: 430ms	remaining: 1.23s
259:	learn: 0.3098940	total: 431ms	remaining: 1.23s
260:	learn: 0.3093980	total: 433ms	remaining: 1.23s
261:	learn: 0.3091904	total: 434ms	remaining: 1.22s
262:	learn: 0.3086312	total: 436ms	remaining: 1.22s
263:	learn: 0.3082349	total: 437ms	remaining: 1.22s
264:	learn: 0.3076565	total: 439ms	remaining: 1.22s
265:	learn: 0.3073168	total: 440ms	remaining: 1.21s
266:	learn: 0.3068957	total: 442ms	remaining: 1.21s
267:	learn: 0.3063833	total: 443ms	remaining: 1.21s
268:	learn: 0.3059531	total: 444ms	remaining: 1.21s
269:	learn: 0.3055655	total: 446ms	remaining: 1.21s
270:	learn: 0.3051240	total: 447ms	remaining: 1.2s
271:	learn: 0.3045580	total: 449ms	remaining: 1.2s
272:	learn: 0.3041421	total: 450ms	remaining: 1.2s
273:	learn: 0.3038117	total: 452ms	remaining: 1.2s
274:	learn: 0.3032116	total: 453ms	remaining: 1.19s
275:	learn: 0.3029128	total: 455ms	remaining: 1.19s
276:	learn: 0.3024802	total: 456ms	remaining: 1.19s
277:	learn: 0.3020364	total: 457ms	remaining: 1.19s
278:	learn: 0.3016911	total: 459ms	remaining: 1.19s
279:	learn: 0.3011550	total: 460ms	remaining: 1.18s
280:	learn: 0.3007675	total: 462ms	remaining: 1.18s
281:	learn: 0.3001772	total: 463ms	remaining: 1.18s
282:	learn: 0.2997739	total: 464ms	remaining: 1.18s
283:	learn: 0.2993443	total: 466ms	remaining: 1.17s
284:	learn: 0.2989274	total: 467ms	remaining: 1.17s
285:	learn: 0.2984021	total: 469ms	remaining: 1.17s
286:	learn: 0.2978414	total: 470ms	remaining: 1.17s
287:	learn: 0.2975345	total: 472ms	remaining: 1.17s
288:	learn: 0.2973059	total: 473ms	remaining: 1.16s
289:	learn: 0.2965193	total: 475ms	remaining: 1.16s
290:	learn: 0.2961698	total: 476ms	remaining: 1.16s
291:	learn: 0.2957314	total: 477ms	remaining: 1.16s
292:	learn: 0.2953507	total: 479ms	remaining: 1.16s
293:	learn: 0.2949769	total: 480ms	remaining: 1.15s
294:	learn: 0.2945714	total: 482ms	remaining: 1.15s
295:	learn: 0.2941183	total: 483ms	remaining: 1.15s
296:	learn: 0.2936217	total: 485ms	remaining: 1.15s
297:	learn: 0.2933841	total: 486ms	remaining: 1.15s
298:	learn: 0.2930709	total: 488ms	remaining: 1.14s
299:	learn: 0.2927083	total: 489ms	remaining: 1.14s
300:	learn: 0.2922362	total: 491ms	remaining: 1.14s
301:	learn: 0.2919516	total: 492ms	remaining: 1.14s
302:	learn: 0.2916877	total: 493ms	remaining: 1.13s
303:	learn: 0.2912414	total: 495ms	remaining: 1.13s
304:	learn: 0.2909716	total: 496ms	remaining: 1.13s
305:	learn: 0.2906331	total: 498ms	remaining: 1.13s
306:	learn: 0.2903819	total: 499ms	remaining: 1.13s
307:	learn: 0.2900908	total: 501ms	remaining: 1.12s
308:	learn: 0.2896272	total: 502ms	remaining: 1.12s
309:	learn: 0.2892379	total: 504ms	remaining: 1.12s
310:	learn: 0.2889962	total: 505ms	remaining: 1.12s
311:	learn: 0.2887973	total: 507ms	remaining: 1.12s
312:	learn: 0.2884287	total: 508ms	remaining: 1.11s
313:	learn: 0.2880582	total: 509ms	remaining: 1.11s
314:	learn: 0.2876728	total: 511ms	remaining: 1.11s
315:	learn: 0.2871883	total: 512ms	remaining: 1.11s
316:	learn: 0.2868924	total: 514ms	remaining: 1.11s
317:	learn: 0.2865376	total: 515ms	remaining: 1.1s
318:	learn: 0.2861789	total: 517ms	remaining: 1.1s
319:	learn: 0.2858599	total: 518ms	remaining: 1.1s
320:	learn: 0.2855359	total: 519ms	remaining: 1.1s
321:	learn: 0.2851896	total: 521ms	remaining: 1.1s
322:	learn: 0.2848709	total: 522ms	remaining: 1.09s
323:	learn: 0.2842373	total: 524ms	remaining: 1.09s
324:	learn: 0.2839514	total: 525ms	remaining: 1.09s
325:	learn: 0.2835960	total: 527ms	remaining: 1.09s
326:	learn: 0.2830974	total: 528ms	remaining: 1.09s
327:	learn: 0.2827690	total: 529ms	remaining: 1.08s
328:	learn: 0.2824859	total: 531ms	remaining: 1.08s
329:	learn: 0.2821533	total: 532ms	remaining: 1.08s
330:	learn: 0.2818807	total: 534ms	remaining: 1.08s
331:	learn: 0.2815065	total: 535ms	remaining: 1.08s
332:	learn: 0.2811537	total: 537ms	remaining: 1.07s
333:	learn: 0.2809809	total: 538ms	remaining: 1.07s
334:	learn: 0.2806668	total: 539ms	remaining: 1.07s
335:	learn: 0.2802261	total: 541ms	remaining: 1.07s
336:	learn: 0.2799213	total: 543ms	remaining: 1.07s
337:	learn: 0.2795183	total: 544ms	remaining: 1.06s
338:	learn: 0.2793545	total: 546ms	remaining: 1.06s
339:	learn: 0.2789227	total: 547ms	remaining: 1.06s
340:	learn: 0.2786106	total: 548ms	remaining: 1.06s
341:	learn: 0.2783832	total: 550ms	remaining: 1.06s
342:	learn: 0.2781669	total: 551ms	remaining: 1.05s
343:	learn: 0.2779966	total: 553ms	remaining: 1.05s
344:	learn: 0.2777125	total: 554ms	remaining: 1.05s
345:	learn: 0.2772259	total: 556ms	remaining: 1.05s
346:	learn: 0.2767687	total: 557ms	remaining: 1.05s
347:	learn: 0.2762630	total: 558ms	remaining: 1.05s
348:	learn: 0.2760254	total: 560ms	remaining: 1.04s
349:	learn: 0.2757494	total: 561ms	remaining: 1.04s
350:	learn: 0.2754384	total: 563ms	remaining: 1.04s
351:	learn: 0.2751967	total: 564ms	remaining: 1.04s
352:	learn: 0.2748762	total: 566ms	remaining: 1.04s
353:	learn: 0.2745104	total: 567ms	remaining: 1.03s
354:	learn: 0.2742321	total: 569ms	remaining: 1.03s
355:	learn: 0.2738357	total: 570ms	remaining: 1.03s
356:	learn: 0.2734977	total: 571ms	remaining: 1.03s
357:	learn: 0.2730815	total: 573ms	remaining: 1.03s
358:	learn: 0.2726740	total: 574ms	remaining: 1.02s
359:	learn: 0.2723033	total: 576ms	remaining: 1.02s
360:	learn: 0.2720657	total: 578ms	remaining: 1.02s
361:	learn: 0.2718396	total: 579ms	remaining: 1.02s
362:	learn: 0.2713709	total: 581ms	remaining: 1.02s
363:	learn: 0.2710567	total: 582ms	remaining: 1.02s
364:	learn: 0.2705448	total: 583ms	remaining: 1.01s
365:	learn: 0.2701858	total: 585ms	remaining: 1.01s
366:	learn: 0.2698907	total: 586ms	remaining: 1.01s
367:	learn: 0.2692829	total: 588ms	remaining: 1.01s
368:	learn: 0.2690525	total: 589ms	remaining: 1.01s
369:	learn: 0.2688711	total: 591ms	remaining: 1s
370:	learn: 0.2684397	total: 592ms	remaining: 1s
371:	learn: 0.2681352	total: 593ms	remaining: 1s
372:	learn: 0.2679269	total: 595ms	remaining: 1000ms
373:	learn: 0.2676029	total: 596ms	remaining: 998ms
374:	learn: 0.2672982	total: 598ms	remaining: 996ms
375:	learn: 0.2670834	total: 599ms	remaining: 994ms
376:	learn: 0.2666383	total: 601ms	remaining: 993ms
377:	learn: 0.2664735	total: 602ms	remaining: 991ms
378:	learn: 0.2661978	total: 603ms	remaining: 989ms
379:	learn: 0.2658313	total: 605ms	remaining: 987ms
380:	learn: 0.2655366	total: 606ms	remaining: 985ms
381:	learn: 0.2652192	total: 608ms	remaining: 983ms
382:	learn: 0.2648306	total: 609ms	remaining: 981ms
383:	learn: 0.2645656	total: 611ms	remaining: 980ms
384:	learn: 0.2643649	total: 612ms	remaining: 978ms
385:	learn: 0.2640850	total: 614ms	remaining: 976ms

## 4.2 Pearson correlation
For pairs of features with $\left| p \right|$ > 0.8, we retain the one with the higher feature importance score

In [29]:
selected_features = Bset['feature'].head(11).tolist()
X_s = X[selected_features]
X_s

,minimum neighbor distance variation,MagpieData minimum AtomicWeight,max packing efficiency,MagpieData maximum CovalentRadius,MagpieData mean Number,MagpieData minimum Number,min relative bond length,mean neighbor distance variation,MagpieData mean Row,MagpieData avg_dev MeltingT,MagpieData avg_dev Electronegativity
0,5.462055e-02,32.0650,0.311138,244.0,31.571429,16.0,0.924097,0.159347,4.000000,217.458776,0.465306
1,1.209678e-02,39.0983,0.384463,203.0,31.200000,19.0,0.787531,0.090941,4.000000,296.933600,0.741600
2,1.054413e-07,6.9410,0.363430,145.0,17.000000,3.0,0.870218,0.132359,2.750000,395.405000,1.262500
3,4.406832e-02,121.7600,0.446026,144.0,59.333333,51.0,0.920416,0.100005,5.333333,1067.653333,0.066667
4,1.442192e-16,6.9410,0.353018,145.0,14.333333,3.0,0.903046,0.102068,2.500000,351.471111,1.122222
...,...,...,...,...,...,...,...,...,...,...,...
656,1.559733e-01,78.9600,0.312321,145.0,40.285714,34.0,0.944346,0.183286,4.428571,101.564694,0.364898
657,5.657788e-03,72.6400,0.488542,146.0,60.750000,32.0,0.973891,0.025433,5.250000,118.354063,0.116250
658,9.032000e-02,32.0650,0.354918,145.0,46.285714,16.0,0.881517,0.136979,4.428571,155.211429,0.421224
659,6.322125e-04,6.9410,0.360448,139.0,11.777778,3.0,0.830062,0.115505,2.333333,381.471111,1.152593
660,9.667138e-02,32.0650,0.367918,145.0,48.857143,16.0,0.919246,0.130759,4.571429,132.408980,0.417551

In [30]:
cab = CatBoostClassifier(random_state=1998) 
model = cab.fit(X_s, y)

Learning rate set to 0.008633
0:	learn: 0.6868063	total: 4.98ms	remaining: 4.98s
1:	learn: 0.6812928	total: 8.23ms	remaining: 4.11s
2:	learn: 0.6758978	total: 11.3ms	remaining: 3.75s
3:	learn: 0.6705456	total: 14.2ms	remaining: 3.54s
4:	learn: 0.6649557	total: 17.1ms	remaining: 3.4s
5:	learn: 0.6592224	total: 20ms	remaining: 3.31s
6:	learn: 0.6550556	total: 22.7ms	remaining: 3.21s
7:	learn: 0.6509005	total: 25.4ms	remaining: 3.15s
8:	learn: 0.6467368	total: 28.2ms	remaining: 3.1s
9:	learn: 0.6417643	total: 30.7ms	remaining: 3.04s
10:	learn: 0.6365030	total: 33.1ms	remaining: 2.98s
11:	learn: 0.6316053	total: 35.6ms	remaining: 2.93s
12:	learn: 0.6263937	total: 38.2ms	remaining: 2.9s
13:	learn: 0.6217043	total: 40.6ms	remaining: 2.86s
14:	learn: 0.6169154	total: 43ms	remaining: 2.82s
15:	learn: 0.6130683	total: 45.4ms	remaining: 2.79s
16:	learn: 0.6086630	total: 47.8ms	remaining: 2.76s
17:	learn: 0.6048446	total: 50.5ms	remaining: 2.75s
18:	learn: 0.6007322	total: 52.8ms	remaining: 2.73s
19:	learn: 0.5961396	total: 55.2ms	remaining: 2.7s
20:	learn: 0.5918052	total: 57.5ms	remaining: 2.68s
21:	learn: 0.5875528	total: 59.8ms	remaining: 2.66s
22:	learn: 0.5834094	total: 62.1ms	remaining: 2.64s
23:	learn: 0.5798542	total: 64.6ms	remaining: 2.63s
24:	learn: 0.5762679	total: 66.9ms	remaining: 2.61s
25:	learn: 0.5729330	total: 69ms	remaining: 2.58s
26:	learn: 0.5696697	total: 71.3ms	remaining: 2.57s
27:	learn: 0.5665065	total: 73.5ms	remaining: 2.55s
28:	learn: 0.5637303	total: 75.5ms	remaining: 2.53s
29:	learn: 0.5607769	total: 77.6ms	remaining: 2.51s
30:	learn: 0.5576821	total: 79.6ms	remaining: 2.49s
31:	learn: 0.5539306	total: 81.8ms	remaining: 2.47s
32:	learn: 0.5507688	total: 84ms	remaining: 2.46s
33:	learn: 0.5471665	total: 86.1ms	remaining: 2.44s
34:	learn: 0.5449035	total: 88.1ms	remaining: 2.43s
35:	learn: 0.5415194	total: 90.2ms	remaining: 2.42s
36:	learn: 0.5388734	total: 92.3ms	remaining: 2.4s
37:	learn: 0.5359670	total: 94.4ms	remaining: 2.39s
38:	learn: 0.5335742	total: 96.4ms	remaining: 2.38s
39:	learn: 0.5308468	total: 98.5ms	remaining: 2.36s
40:	learn: 0.5277562	total: 100ms	remaining: 2.35s
41:	learn: 0.5248415	total: 102ms	remaining: 2.33s
42:	learn: 0.5228280	total: 104ms	remaining: 2.32s
43:	learn: 0.5208114	total: 106ms	remaining: 2.31s
44:	learn: 0.5172780	total: 108ms	remaining: 2.29s
45:	learn: 0.5142645	total: 110ms	remaining: 2.27s
46:	learn: 0.5115768	total: 111ms	remaining: 2.26s
47:	learn: 0.5093554	total: 113ms	remaining: 2.25s
48:	learn: 0.5075122	total: 115ms	remaining: 2.23s
49:	learn: 0.5041893	total: 117ms	remaining: 2.22s
50:	learn: 0.5021040	total: 118ms	remaining: 2.2s
51:	learn: 0.5001846	total: 120ms	remaining: 2.19s
52:	learn: 0.4985461	total: 122ms	remaining: 2.18s
53:	learn: 0.4960882	total: 124ms	remaining: 2.17s
54:	learn: 0.4941256	total: 125ms	remaining: 2.15s
55:	learn: 0.4918845	total: 127ms	remaining: 2.15s
56:	learn: 0.4898719	total: 129ms	remaining: 2.13s
57:	learn: 0.4878359	total: 131ms	remaining: 2.12s
58:	learn: 0.4862364	total: 132ms	remaining: 2.11s
59:	learn: 0.4842378	total: 134ms	remaining: 2.1s
60:	learn: 0.4821941	total: 136ms	remaining: 2.09s
61:	learn: 0.4799285	total: 138ms	remaining: 2.08s
62:	learn: 0.4780338	total: 139ms	remaining: 2.07s
63:	learn: 0.4755499	total: 141ms	remaining: 2.06s
64:	learn: 0.4740062	total: 142ms	remaining: 2.05s
65:	learn: 0.4723031	total: 144ms	remaining: 2.04s
66:	learn: 0.4704614	total: 146ms	remaining: 2.03s
67:	learn: 0.4690027	total: 147ms	remaining: 2.02s
68:	learn: 0.4668537	total: 149ms	remaining: 2.01s
69:	learn: 0.4651212	total: 151ms	remaining: 2s
70:	learn: 0.4632073	total: 152ms	remaining: 1.99s
71:	learn: 0.4613660	total: 154ms	remaining: 1.98s
72:	learn: 0.4595030	total: 155ms	remaining: 1.97s
73:	learn: 0.4573420	total: 157ms	remaining: 1.97s
74:	learn: 0.4559645	total: 159ms	remaining: 1.96s
75:	learn: 0.4543553	total: 160ms	remaining: 1.95s
76:	learn: 0.4524391	total: 162ms	remaining: 1.94s
77:	learn: 0.4507222	total: 164ms	remaining: 1.94s
78:	learn: 0.4487772	total: 165ms	remaining: 1.93s
79:	learn: 0.4477695	total: 167ms	remaining: 1.92s
80:	learn: 0.4465919	total: 169ms	remaining: 1.91s
81:	learn: 0.4451288	total: 170ms	remaining: 1.9s
82:	learn: 0.4434245	total: 172ms	remaining: 1.9s
83:	learn: 0.4418722	total: 173ms	remaining: 1.89s
84:	learn: 0.4407186	total: 175ms	remaining: 1.88s
85:	learn: 0.4389348	total: 176ms	remaining: 1.87s
86:	learn: 0.4375034	total: 178ms	remaining: 1.86s
87:	learn: 0.4363340	total: 179ms	remaining: 1.86s
88:	learn: 0.4347666	total: 181ms	remaining: 1.85s
89:	learn: 0.4331710	total: 182ms	remaining: 1.84s
90:	learn: 0.4320301	total: 184ms	remaining: 1.83s
91:	learn: 0.4310653	total: 185ms	remaining: 1.83s
92:	learn: 0.4297671	total: 187ms	remaining: 1.82s
93:	learn: 0.4284226	total: 188ms	remaining: 1.81s
94:	learn: 0.4273159	total: 190ms	remaining: 1.81s
95:	learn: 0.4259672	total: 191ms	remaining: 1.8s
96:	learn: 0.4246349	total: 193ms	remaining: 1.8s
97:	learn: 0.4234098	total: 195ms	remaining: 1.79s
98:	learn: 0.4223155	total: 196ms	remaining: 1.79s
99:	learn: 0.4211367	total: 198ms	remaining: 1.78s
100:	learn: 0.4200771	total: 199ms	remaining: 1.77s
101:	learn: 0.4188876	total: 201ms	remaining: 1.77s
102:	learn: 0.4174577	total: 202ms	remaining: 1.76s
103:	learn: 0.4163239	total: 204ms	remaining: 1.75s
104:	learn: 0.4149259	total: 205ms	remaining: 1.75s
105:	learn: 0.4137191	total: 206ms	remaining: 1.74s
106:	learn: 0.4122463	total: 208ms	remaining: 1.74s
107:	learn: 0.4111451	total: 209ms	remaining: 1.73s
108:	learn: 0.4099826	total: 211ms	remaining: 1.72s
109:	learn: 0.4091007	total: 212ms	remaining: 1.72s
110:	learn: 0.4080215	total: 214ms	remaining: 1.71s
111:	learn: 0.4068404	total: 215ms	remaining: 1.71s
112:	learn: 0.4054103	total: 217ms	remaining: 1.7s
113:	learn: 0.4040220	total: 219ms	remaining: 1.7s
114:	learn: 0.4028329	total: 220ms	remaining: 1.69s
115:	learn: 0.4018848	total: 221ms	remaining: 1.69s
116:	learn: 0.4009882	total: 223ms	remaining: 1.68s
117:	learn: 0.4000536	total: 224ms	remaining: 1.68s
118:	learn: 0.3990317	total: 226ms	remaining: 1.67s
119:	learn: 0.3981393	total: 227ms	remaining: 1.67s
120:	learn: 0.3974232	total: 229ms	remaining: 1.66s
121:	learn: 0.3960804	total: 230ms	remaining: 1.66s
122:	learn: 0.3950145	total: 232ms	remaining: 1.65s
123:	learn: 0.3940914	total: 233ms	remaining: 1.65s
124:	learn: 0.3935191	total: 235ms	remaining: 1.64s
125:	learn: 0.3923166	total: 236ms	remaining: 1.64s
126:	learn: 0.3910324	total: 238ms	remaining: 1.63s
127:	learn: 0.3902400	total: 239ms	remaining: 1.63s
128:	learn: 0.3891961	total: 241ms	remaining: 1.62s
129:	learn: 0.3879782	total: 242ms	remaining: 1.62s
130:	learn: 0.3869261	total: 244ms	remaining: 1.61s
131:	learn: 0.3860319	total: 245ms	remaining: 1.61s
132:	learn: 0.3852521	total: 246ms	remaining: 1.61s
133:	learn: 0.3843971	total: 248ms	remaining: 1.6s
134:	learn: 0.3832458	total: 249ms	remaining: 1.6s
135:	learn: 0.3823754	total: 251ms	remaining: 1.59s
136:	learn: 0.3815426	total: 252ms	remaining: 1.59s
137:	learn: 0.3810486	total: 254ms	remaining: 1.58s
138:	learn: 0.3801633	total: 255ms	remaining: 1.58s
139:	learn: 0.3793451	total: 257ms	remaining: 1.58s
140:	learn: 0.3786524	total: 258ms	remaining: 1.57s
141:	learn: 0.3779203	total: 260ms	remaining: 1.57s
142:	learn: 0.3772618	total: 262ms	remaining: 1.57s
143:	learn: 0.3765923	total: 263ms	remaining: 1.56s
144:	learn: 0.3758008	total: 264ms	remaining: 1.56s
145:	learn: 0.3747170	total: 266ms	remaining: 1.55s
146:	learn: 0.3740392	total: 267ms	remaining: 1.55s
147:	learn: 0.3733701	total: 269ms	remaining: 1.55s
148:	learn: 0.3725845	total: 270ms	remaining: 1.54s
149:	learn: 0.3717567	total: 272ms	remaining: 1.54s
150:	learn: 0.3710595	total: 273ms	remaining: 1.53s
151:	learn: 0.3701738	total: 274ms	remaining: 1.53s
152:	learn: 0.3692055	total: 276ms	remaining: 1.53s
153:	learn: 0.3682013	total: 277ms	remaining: 1.52s
154:	learn: 0.3672545	total: 279ms	remaining: 1.52s
155:	learn: 0.3663512	total: 280ms	remaining: 1.51s
156:	learn: 0.3656602	total: 282ms	remaining: 1.51s
157:	learn: 0.3650793	total: 283ms	remaining: 1.51s
158:	learn: 0.3644139	total: 284ms	remaining: 1.5s
159:	learn: 0.3638223	total: 286ms	remaining: 1.5s
160:	learn: 0.3632027	total: 287ms	remaining: 1.5s
161:	learn: 0.3626933	total: 289ms	remaining: 1.49s
162:	learn: 0.3617617	total: 290ms	remaining: 1.49s
163:	learn: 0.3610805	total: 292ms	remaining: 1.49s
164:	learn: 0.3604329	total: 293ms	remaining: 1.48s
165:	learn: 0.3598837	total: 295ms	remaining: 1.48s
166:	learn: 0.3593898	total: 296ms	remaining: 1.48s
167:	learn: 0.3587886	total: 298ms	remaining: 1.47s
168:	learn: 0.3582200	total: 299ms	remaining: 1.47s
169:	learn: 0.3573853	total: 301ms	remaining: 1.47s
170:	learn: 0.3567392	total: 302ms	remaining: 1.46s
171:	learn: 0.3560280	total: 303ms	remaining: 1.46s
172:	learn: 0.3556081	total: 305ms	remaining: 1.46s
173:	learn: 0.3550234	total: 306ms	remaining: 1.45s
174:	learn: 0.3543943	total: 308ms	remaining: 1.45s
175:	learn: 0.3539110	total: 309ms	remaining: 1.45s
176:	learn: 0.3531533	total: 311ms	remaining: 1.45s
177:	learn: 0.3524462	total: 312ms	remaining: 1.44s
178:	learn: 0.3518417	total: 314ms	remaining: 1.44s
179:	learn: 0.3512534	total: 315ms	remaining: 1.44s
180:	learn: 0.3505742	total: 317ms	remaining: 1.43s
181:	learn: 0.3499922	total: 318ms	remaining: 1.43s
182:	learn: 0.3496688	total: 320ms	remaining: 1.43s
183:	learn: 0.3491694	total: 321ms	remaining: 1.42s
184:	learn: 0.3487327	total: 322ms	remaining: 1.42s
185:	learn: 0.3483921	total: 324ms	remaining: 1.42s
186:	learn: 0.3475343	total: 325ms	remaining: 1.41s
187:	learn: 0.3472412	total: 327ms	remaining: 1.41s
188:	learn: 0.3464905	total: 328ms	remaining: 1.41s
189:	learn: 0.3458920	total: 330ms	remaining: 1.41s
190:	learn: 0.3450464	total: 331ms	remaining: 1.4s
191:	learn: 0.3446252	total: 333ms	remaining: 1.4s
192:	learn: 0.3436254	total: 334ms	remaining: 1.4s
193:	learn: 0.3430431	total: 335ms	remaining: 1.39s
194:	learn: 0.3424803	total: 337ms	remaining: 1.39s
195:	learn: 0.3420225	total: 338ms	remaining: 1.39s
196:	learn: 0.3413475	total: 340ms	remaining: 1.39s
197:	learn: 0.3409066	total: 341ms	remaining: 1.38s
198:	learn: 0.3403591	total: 343ms	remaining: 1.38s
199:	learn: 0.3397040	total: 344ms	remaining: 1.38s
200:	learn: 0.3389427	total: 346ms	remaining: 1.37s
201:	learn: 0.3381442	total: 347ms	remaining: 1.37s
202:	learn: 0.3376834	total: 349ms	remaining: 1.37s
203:	learn: 0.3370046	total: 350ms	remaining: 1.37s
204:	learn: 0.3365909	total: 352ms	remaining: 1.36s
205:	learn: 0.3360627	total: 353ms	remaining: 1.36s
206:	learn: 0.3354059	total: 355ms	remaining: 1.36s
207:	learn: 0.3350063	total: 356ms	remaining: 1.35s
208:	learn: 0.3342671	total: 357ms	remaining: 1.35s
209:	learn: 0.3338259	total: 359ms	remaining: 1.35s
210:	learn: 0.3331777	total: 360ms	remaining: 1.35s
211:	learn: 0.3326870	total: 362ms	remaining: 1.34s
212:	learn: 0.3321537	total: 363ms	remaining: 1.34s
213:	learn: 0.3317527	total: 365ms	remaining: 1.34s
214:	learn: 0.3312557	total: 366ms	remaining: 1.34s
215:	learn: 0.3309204	total: 368ms	remaining: 1.33s
216:	learn: 0.3302733	total: 369ms	remaining: 1.33s
217:	learn: 0.3297544	total: 371ms	remaining: 1.33s
218:	learn: 0.3292587	total: 372ms	remaining: 1.33s
219:	learn: 0.3284913	total: 373ms	remaining: 1.32s
220:	learn: 0.3281179	total: 375ms	remaining: 1.32s
221:	learn: 0.3276168	total: 376ms	remaining: 1.32s
222:	learn: 0.3271753	total: 378ms	remaining: 1.32s
223:	learn: 0.3267949	total: 379ms	remaining: 1.31s
224:	learn: 0.3263383	total: 381ms	remaining: 1.31s
225:	learn: 0.3257762	total: 382ms	remaining: 1.31s
226:	learn: 0.3251513	total: 384ms	remaining: 1.31s
227:	learn: 0.3247096	total: 385ms	remaining: 1.3s
228:	learn: 0.3239920	total: 387ms	remaining: 1.3s
229:	learn: 0.3236817	total: 388ms	remaining: 1.3s
230:	learn: 0.3232248	total: 390ms	remaining: 1.3s
231:	learn: 0.3228007	total: 391ms	remaining: 1.29s
232:	learn: 0.3224389	total: 393ms	remaining: 1.29s
233:	learn: 0.3219272	total: 394ms	remaining: 1.29s
234:	learn: 0.3214683	total: 396ms	remaining: 1.29s
235:	learn: 0.3211474	total: 397ms	remaining: 1.28s
236:	learn: 0.3207496	total: 398ms	remaining: 1.28s
237:	learn: 0.3203999	total: 400ms	remaining: 1.28s
238:	learn: 0.3199174	total: 401ms	remaining: 1.28s
239:	learn: 0.3194774	total: 403ms	remaining: 1.27s
240:	learn: 0.3190775	total: 404ms	remaining: 1.27s
241:	learn: 0.3188412	total: 406ms	remaining: 1.27s
242:	learn: 0.3184795	total: 407ms	remaining: 1.27s
243:	learn: 0.3182469	total: 409ms	remaining: 1.26s
244:	learn: 0.3177690	total: 410ms	remaining: 1.26s
245:	learn: 0.3173168	total: 412ms	remaining: 1.26s
246:	learn: 0.3168744	total: 413ms	remaining: 1.26s
247:	learn: 0.3163983	total: 414ms	remaining: 1.26s
248:	learn: 0.3160999	total: 416ms	remaining: 1.25s
249:	learn: 0.3157810	total: 417ms	remaining: 1.25s
250:	learn: 0.3152111	total: 419ms	remaining: 1.25s
251:	learn: 0.3147286	total: 420ms	remaining: 1.25s
252:	learn: 0.3143678	total: 422ms	remaining: 1.24s
253:	learn: 0.3140400	total: 423ms	remaining: 1.24s
254:	learn: 0.3134209	total: 424ms	remaining: 1.24s
255:	learn: 0.3128595	total: 426ms	remaining: 1.24s
256:	learn: 0.3122996	total: 427ms	remaining: 1.24s
257:	learn: 0.3119889	total: 429ms	remaining: 1.23s
258:	learn: 0.3114510	total: 430ms	remaining: 1.23s
259:	learn: 0.3110641	total: 432ms	remaining: 1.23s
260:	learn: 0.3107588	total: 433ms	remaining: 1.23s
261:	learn: 0.3103100	total: 435ms	remaining: 1.22s
262:	learn: 0.3100060	total: 436ms	remaining: 1.22s
263:	learn: 0.3095485	total: 437ms	remaining: 1.22s
264:	learn: 0.3092757	total: 439ms	remaining: 1.22s
265:	learn: 0.3087609	total: 440ms	remaining: 1.22s
266:	learn: 0.3083863	total: 442ms	remaining: 1.21s
267:	learn: 0.3079829	total: 443ms	remaining: 1.21s
268:	learn: 0.3074638	total: 445ms	remaining: 1.21s
269:	learn: 0.3069235	total: 446ms	remaining: 1.21s
270:	learn: 0.3065326	total: 448ms	remaining: 1.2s
271:	learn: 0.3060855	total: 449ms	remaining: 1.2s
272:	learn: 0.3058353	total: 451ms	remaining: 1.2s
273:	learn: 0.3051870	total: 452ms	remaining: 1.2s
274:	learn: 0.3048207	total: 453ms	remaining: 1.2s
275:	learn: 0.3045511	total: 455ms	remaining: 1.19s
276:	learn: 0.3042653	total: 456ms	remaining: 1.19s
277:	learn: 0.3038665	total: 458ms	remaining: 1.19s
278:	learn: 0.3034697	total: 459ms	remaining: 1.19s
279:	learn: 0.3031993	total: 461ms	remaining: 1.18s
280:	learn: 0.3027998	total: 462ms	remaining: 1.18s
281:	learn: 0.3024437	total: 464ms	remaining: 1.18s
282:	learn: 0.3021330	total: 465ms	remaining: 1.18s
283:	learn: 0.3016709	total: 466ms	remaining: 1.18s
284:	learn: 0.3011945	total: 468ms	remaining: 1.17s
285:	learn: 0.3008741	total: 469ms	remaining: 1.17s
286:	learn: 0.3004311	total: 471ms	remaining: 1.17s
287:	learn: 0.2998973	total: 472ms	remaining: 1.17s
288:	learn: 0.2994058	total: 474ms	remaining: 1.17s
289:	learn: 0.2990805	total: 475ms	remaining: 1.16s
290:	learn: 0.2987480	total: 476ms	remaining: 1.16s
291:	learn: 0.2982928	total: 478ms	remaining: 1.16s
292:	learn: 0.2979572	total: 479ms	remaining: 1.16s
293:	learn: 0.2974453	total: 481ms	remaining: 1.15s
294:	learn: 0.2970546	total: 482ms	remaining: 1.15s
295:	learn: 0.2966464	total: 484ms	remaining: 1.15s
296:	learn: 0.2963747	total: 485ms	remaining: 1.15s
297:	learn: 0.2960105	total: 486ms	remaining: 1.15s
298:	learn: 0.2954492	total: 488ms	remaining: 1.14s
299:	learn: 0.2951250	total: 489ms	remaining: 1.14s
300:	learn: 0.2946036	total: 491ms	remaining: 1.14s
301:	learn: 0.2943419	total: 492ms	remaining: 1.14s
302:	learn: 0.2939270	total: 494ms	remaining: 1.14s
303:	learn: 0.2935042	total: 495ms	remaining: 1.13s
304:	learn: 0.2931135	total: 496ms	remaining: 1.13s
305:	learn: 0.2927883	total: 498ms	remaining: 1.13s
306:	learn: 0.2923219	total: 499ms	remaining: 1.13s
307:	learn: 0.2921097	total: 501ms	remaining: 1.13s
308:	learn: 0.2915551	total: 502ms	remaining: 1.12s
309:	learn: 0.2912733	total: 504ms	remaining: 1.12s
310:	learn: 0.2910090	total: 505ms	remaining: 1.12s
311:	learn: 0.2908236	total: 507ms	remaining: 1.12s
312:	learn: 0.2903421	total: 508ms	remaining: 1.11s
313:	learn: 0.2899165	total: 510ms	remaining: 1.11s
314:	learn: 0.2895694	total: 511ms	remaining: 1.11s
315:	learn: 0.2892870	total: 512ms	remaining: 1.11s
316:	learn: 0.2890024	total: 514ms	remaining: 1.11s
317:	learn: 0.2885289	total: 515ms	remaining: 1.1s
318:	learn: 0.2880937	total: 517ms	remaining: 1.1s
319:	learn: 0.2878003	total: 518ms	remaining: 1.1s
320:	learn: 0.2875194	total: 520ms	remaining: 1.1s
321:	learn: 0.2870786	total: 521ms	remaining: 1.1s
322:	learn: 0.2867774	total: 522ms	remaining: 1.09s
323:	learn: 0.2865046	total: 524ms	remaining: 1.09s
324:	learn: 0.2862342	total: 525ms	remaining: 1.09s
325:	learn: 0.2859772	total: 527ms	remaining: 1.09s
326:	learn: 0.2855210	total: 528ms	remaining: 1.09s
327:	learn: 0.2852344	total: 530ms	remaining: 1.08s
328:	learn: 0.2848553	total: 531ms	remaining: 1.08s
329:	learn: 0.2842982	total: 533ms	remaining: 1.08s
330:	learn: 0.2840220	total: 534ms	remaining: 1.08s
331:	learn: 0.2834823	total: 536ms	remaining: 1.08s
332:	learn: 0.2831792	total: 537ms	remaining: 1.07s
333:	learn: 0.2829714	total: 538ms	remaining: 1.07s
334:	learn: 0.2826258	total: 540ms	remaining: 1.07s
335:	learn: 0.2822591	total: 541ms	remaining: 1.07s
336:	learn: 0.2817706	total: 543ms	remaining: 1.07s
337:	learn: 0.2816059	total: 544ms	remaining: 1.06s
338:	learn: 0.2810802	total: 546ms	remaining: 1.06s
339:	learn: 0.2808320	total: 547ms	remaining: 1.06s
340:	learn: 0.2805968	total: 549ms	remaining: 1.06s
341:	learn: 0.2800634	total: 550ms	remaining: 1.06s
342:	learn: 0.2797644	total: 551ms	remaining: 1.06s
343:	learn: 0.2795283	total: 553ms	remaining: 1.05s
344:	learn: 0.2790758	total: 554ms	remaining: 1.05s
345:	learn: 0.2786635	total: 556ms	remaining: 1.05s
346:	learn: 0.2782841	total: 557ms	remaining: 1.05s
347:	learn: 0.2780371	total: 559ms	remaining: 1.05s
348:	learn: 0.2778270	total: 560ms	remaining: 1.04s
349:	learn: 0.2774459	total: 562ms	remaining: 1.04s
350:	learn: 0.2771472	total: 563ms	remaining: 1.04s
351:	learn: 0.2768431	total: 565ms	remaining: 1.04s
352:	learn: 0.2764396	total: 566ms	remaining: 1.04s
353:	learn: 0.2762260	total: 568ms	remaining: 1.03s
354:	learn: 0.2759665	total: 569ms	remaining: 1.03s
355:	learn: 0.2756147	total: 570ms	remaining: 1.03s
356:	learn: 0.2754121	total: 572ms	remaining: 1.03s
357:	learn: 0.2750136	total: 573ms	remaining: 1.03s
358:	learn: 0.2746058	total: 575ms	remaining: 1.03s
359:	learn: 0.2743144	total: 576ms	remaining: 1.02s
360:	learn: 0.2740361	total: 578ms	remaining: 1.02s
361:	learn: 0.2738262	total: 579ms	remaining: 1.02s
362:	learn: 0.2734676	total: 581ms	remaining: 1.02s
363:	learn: 0.2731734	total: 582ms	remaining: 1.02s
364:	learn: 0.2728631	total: 584ms	remaining: 1.01s
365:	learn: 0.2725236	total: 585ms	remaining: 1.01s
366:	learn: 0.2720686	total: 587ms	remaining: 1.01s
367:	learn: 0.2717666	total: 588ms	remaining: 1.01s
368:	learn: 0.2714358	total: 589ms	remaining: 1.01s
369:	learn: 0.2709759	total: 591ms	remaining: 1.01s
370:	learn: 0.2707907	total: 592ms	remaining: 1s
371:	learn: 0.2705112	total: 594ms	remaining: 1s
372:	learn: 0.2702353	total: 595ms	remaining: 1s
373:	learn: 0.2699925	total: 597ms	remaining: 999ms
374:	learn: 0.2697833	total: 598ms	remaining: 997ms
375:	learn: 0.2694901	total: 599ms	remaining: 995ms
376:	learn: 0.2692276	total: 601ms	remaining: 993ms
377:	learn: 0.2690720	total: 602ms	remaining: 991ms
378:	learn: 0.2687433	total: 604ms	remaining: 989ms
379:	learn: 0.2684027	total: 605ms	remaining: 987ms
380:	learn: 0.2680267	total: 607ms	remaining: 985ms
381:	learn: 0.2676941	total: 608ms	remaining: 984ms
382:	learn: 0.2673271	total: 609ms	remaining: 982ms
383:	learn: 0.2671404	total: 611ms	remaining: 980ms
384:	learn: 0.2667081	total: 612ms	remaining: 978ms
385:	learn: 0.2663532	total: 614ms	remaining: 976ms

In [31]:
Bset = pd.DataFrame()
Bset['feature'] = X_s.columns
Bset['importance'] = model.feature_importances_
Bset = Bset.sort_values(by='importance', ascending=False)
Bset.reset_index(drop=True, inplace=True)
Bset

                                 feature  importance
0            MagpieData avg_dev MeltingT   15.175345
1   MagpieData avg_dev Electronegativity   12.902845
2      MagpieData maximum CovalentRadius    9.739166
3               min relative bond length    9.207217
4                 max packing efficiency    8.664929
5        MagpieData minimum AtomicWeight    8.521726
6    minimum neighbor distance variation    8.020104
7              MagpieData minimum Number    7.232394
8                 MagpieData mean Number    7.172352
9       mean neighbor distance variation    7.064391
10                   MagpieData mean Row    6.299532

In [32]:
correlation_matrix = X_s.corr()

highly_correlated_pairs = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.8:
            highly_correlated_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

for pair in highly_correlated_pairs:
    feature1, feature2 = pair
    
    if feature1 in X_s.columns and feature2 in X_s.columns:
        importance1 = Bset.loc[Bset['feature'] == feature1, 'importance'].values[0]
        importance2 = Bset.loc[Bset['feature'] == feature2, 'importance'].values[0]
        
        if importance1 > importance2:
            X_s = X_s.drop(columns=[feature2])
        else:
            X_s = X_s.drop(columns=[feature1])

X_s

,minimum neighbor distance variation,MagpieData minimum AtomicWeight,max packing efficiency,MagpieData maximum CovalentRadius,MagpieData mean Number,min relative bond length,mean neighbor distance variation,MagpieData avg_dev MeltingT,MagpieData avg_dev Electronegativity
0,5.462055e-02,32.0650,0.311138,244.0,31.571429,0.924097,0.159347,217.458776,0.465306
1,1.209678e-02,39.0983,0.384463,203.0,31.200000,0.787531,0.090941,296.933600,0.741600
2,1.054413e-07,6.9410,0.363430,145.0,17.000000,0.870218,0.132359,395.405000,1.262500
3,4.406832e-02,121.7600,0.446026,144.0,59.333333,0.920416,0.100005,1067.653333,0.066667
4,1.442192e-16,6.9410,0.353018,145.0,14.333333,0.903046,0.102068,351.471111,1.122222
...,...,...,...,...,...,...,...,...,...
656,1.559733e-01,78.9600,0.312321,145.0,40.285714,0.944346,0.183286,101.564694,0.364898
657,5.657788e-03,72.6400,0.488542,146.0,60.750000,0.973891,0.025433,118.354063,0.116250
658,9.032000e-02,32.0650,0.354918,145.0,46.285714,0.881517,0.136979,155.211429,0.421224
659,6.322125e-04,6.9410,0.360448,139.0,11.777778,0.830062,0.115505,381.471111,1.152593
660,9.667138e-02,32.0650,0.367918,145.0,48.857143,0.919246,0.130759,132.408980,0.417551

In [35]:
df_ = pd.concat([df, X_s], axis=1)
df_['k_class'] = 1
df_.loc[df_['k_ao'] > 2, 'k_class'] = 0
df_

,nsites,nelements,formula_pretty,formula_anonymous,volume,density,material_id,energy_per_atom,formation_energy_per_atom,energy_above_hull,...,minimum neighbor distance variation,MagpieData minimum AtomicWeight,max packing efficiency,MagpieData maximum CovalentRadius,MagpieData mean Number,min relative bond length,mean neighbor distance variation,MagpieData avg_dev MeltingT,MagpieData avg_dev Electronegativity,k_class
0,14,3,Cs(SbS2)2,AB2C4,416.924169,4.020155,mp-8890,-16.138279,-0.616589,0.000000,...,5.462055e-02,32.0650,0.311138,244.0,31.571429,0.924097,0.159347,217.458776,0.465306,1
1,5,3,KGeBr3,ABC3,175.640517,3.322678,mp-998412,-3.495008,-1.412312,0.025231,...,1.209678e-02,39.0983,0.384463,203.0,31.200000,0.787531,0.090941,296.933600,0.741600,1
2,4,3,LiAgF2,ABC2,51.295990,4.946592,mp-1176792,-9.631004,-2.133530,0.023437,...,1.054413e-07,6.9410,0.363430,145.0,17.000000,0.870218,0.132359,395.405000,1.262500,1
3,6,2,Sb2Os,AB2,130.076043,11.074427,mp-2695,-34.883281,-0.083994,0.000000,...,4.406832e-02,121.7600,0.446026,144.0,59.333333,0.920416,0.100005,1067.653333,0.066667,0
4,12,3,LiAgF4,ABC4,150.435277,4.212250,mp-752768,-7.883206,-1.843673,0.035738,...,1.442192e-16,6.9410,0.353018,145.0,14.333333,0.903046,0.102068,351.471111,1.122222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
656,14,3,In5AgSe8,AB5C8,408.163709,5.344296,mp-1224092,-3.944965,-0.758815,0.000000,...,1.559733e-01,78.9600,0.312321,145.0,40.285714,0.944346,0.183286,101.564694,0.364898,1
657,8,3,GeTe4Pb3,AB3C4,269.026576,7.435517,mp-1224448,-35.894271,-0.344737,0.042003,...,5.657788e-03,72.6400,0.488542,146.0,60.750000,0.973891,0.025433,118.354063,0.116250,0
658,7,3,Tl3AsS3,AB3C3,193.649007,6.725080,mp-9791,-3.978961,-0.521873,0.006070,...,9.032000e-02,32.0650,0.354918,145.0,46.285714,0.881517,0.136979,155.211429,0.421224,1
659,18,3,Li2PdF6,AB2C6,189.318076,4.110032,mp-13985,-7.451218,-2.287240,0.000000,...,6.322125e-04,6.9410,0.360448,139.0,11.777778,0.830062,0.115505,381.471111,1.152593,1
660,7,3,Tl3SbS3,AB3C3,203.052508,6.796676,mp-8393,-3.928824,-0.549039,0.000000,...,9.667138e-02,32.0650,0.367918,145.0,48.857143,0.919246,0.130759,132.408980,0.417551,1

In [37]:
df_ = df_.drop(['structure'], axis=1)

df_.to_json('./data/MP_C12_selected_features.json')